### ISSUE TITLE
Invalid error response format in case of static validation errors

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1962] opened 2018-11-17 09:54 UTC
Hi,

According to [the GraphQL spec](https://github.com/facebook/graphql/blob/master/spec/Section%207%20--%20Response.md#user-content-errors) the error response format should contain a `path` field containing the ... - well path - to the field which has something to do with the error that occured (such as failed a static validation).

However during static validation the library generates this information under `fields`. This is also inconsistent with the way errors are returned when the execution add an error to the context or throws a `GraphQL::ExecutionError`, in those cases the path is generated correctly under `path`.

I believe what we need to fix is to change the value in this line: https://github.com/rmosolgo/graphql-ruby/blob/4f6d5f9f8feb40ab3790136cce2be20fa50b521c/lib/graphql/static_validation/message.rb#L29

**Comment by axos88** [comment] 2018-11-17 10:01
We are still using the 1.7 branch due to a breaking change in case of enums with a hash inner values that we encountered when upgrading to 1.8, any chance this fix can be backported to 1.7.15(?) as well?

**Comment by rmosolgo** [comment] 2018-11-19 20:54
Oh, that's nice, I didn't notice that it had been formalized. It sounds good to me, but we'll have to let people know in case they're depending on the old field. 

As for 1.7.15, do you need a version on RubyGems? If not, you could always maintain a fork until you can update. If you need a version on RubyGems, I can push a release, too, but please open a PR against the last SHA in the 1.7 version, I think it's https://github.com/rmosolgo/graphql-ruby/commit/9f74912f9b7ba8e898d188a03bf3e2737f4aa7dd

**Comment by krider2010** [comment] 2018-11-20 10:59
I'm working on a PR in this area right now, so can do this for the 1.9 dev branch (where there are already breaking changes) if you want @rmosolgo ? The validation message upgrades will affect this hash anyway.

**Comment by rmosolgo** [comment] 2018-11-20 15:46
Yeah, that'd be great!

**Comment by axos88** [comment] 2018-11-20 23:54
I also noticed that the error response is different when having static validations of a variable. We just finished a large deploy, so I will have some time in the next few days to give you a complete description.

**Comment by krider2010** [comment] 2018-11-21 11:10
Any further info you can provide would be awesome @axos88. Thank you so much!

**Comment by axos88** [comment] 2018-11-27 14:50
Sorry, forgot about this:

```
{
  "errors": [
    {
      "message": "Variable input of type updateAgentInput! was provided invalid value",
      "locations": [
        {
          "line": 1,
          "column": 10
        }
      ],
      "value": {
        "first_name": "Spiderman",
        "id": "invalid_id",
        "email": "invalid_email"
      },
      "problems": [
        {
          "path": [
            "id"
          ],
          "explanation": "Could not coerce value \"invalid_id\" to ObjectId"
        },
        {
          "path": [
            "email"
          ],
          "explanation": "Could not coerce value \"invalid_email\" to Email"
        }
      ]
    }
  ]
}
```

**Comment by axos88** [comment] 2018-11-27 14:51
This happens for this mutation:

```
mutation($input: updateAgentInput!) {
  updateAgent(input: $input) {
    success
  }
}
```

Input is passed in as a variable, as you can see above

**Comment by axos88** [comment] 2018-11-27 14:54
The response is correct for the case when it is inlined:

```
mutation {
  updateAgent(input: {
    first_name: "Spiderman",
    id: "invalid_id",
    email: "invalid_email"
  }) {
    success
  }
}
```

```
{
  "errors": [
    {
      "message": "Argument 'input' on Field 'updateAgent' has an invalid value. Expected type 'updateAgentInput!'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "mutation",
        "updateAgent",
        "input"
      ]
    },
    {
      "message": "Argument 'id' on InputObject 'updateAgentInput' has an invalid value. Expected type 'ObjectId!'.",
      "locations": [
        {
          "line": 2,
          "column": 22
        }
      ],
      "path": [
        "mutation",
        "updateAgent",
        "input",
        "id"
      ]
    },
    {
      "message": "Argument 'email' on InputObject 'updateAgentInput' has an invalid value. Expected type 'Email'.",
      "locations": [
        {
          "line": 2,
          "column": 22
        }
      ],
      "path": [
        "mutation",
        "updateAgent",
        "input",
        "email"
      ]
    }
  ]
}
```

**Comment by modosc** [comment] 2018-12-01 00:37
i think this is a dupe of #1024 ?

**Comment by krider2010** [comment] 2018-12-05 10:49
The `1.9-dev` branch now has the `fields` renamed to `path`

**Comment by bejczib** [comment] 2019-06-11 15:52
Hi,

in my opinion the current usage of the path isn't correct in case of static analysation error.

According to the [spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors), if an error can be associated to a particular field in the GraphQL **result**, it must contain an entry with the key path that details the path of the **response field** which experienced the error. So the path is about the result, not the input. 

In my understanding the `path` shouldn't be in the response when there is an AnalysisError, because it can't point to any field in the response or at least it should point to the operation root. (like when ExecutionError happens) 

However we need to know which field is against the schema. According to the spec every additional data, that is not `message` or `location` should be under the `extensions`. 

```
 {
  "errors": [
    {
      "message": "Argument 'input' on Field 'createFix' has an invalid value. Expected type 'createFixInput!'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": { 
        "field":  "field_name"
      }
    }
  ]
}
```

What do you think about this?

Best,

Balint

**Comment by rmosolgo** [comment] 2020-03-20 14:05
As @krider2010 noted above, we're returning `"path"` in this case now. I made a little script to replicate the error described above: 

```ruby 
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.10.4"
end


class Query < GraphQL::Schema::Object
  field :int, Int, null: true
end

class CreateThing < GraphQL::Schema::RelayClassicMutation
  argument :name, String, required: true
  field :success, Boolean, null: false
end

class Mutation < GraphQL::Schema::Object
  field :create_thing, mutation: CreateThing
end

class Schema < GraphQL::Schema
  query Query
  mutation ::Mutation
end

puts "LITERAL VALUE ERROR"
pp Schema.execute('mutation { createThing(input: { name: 1 }) { success } }').to_h
puts "\n\nVARIABLE VALUE ERROR"
pp Schema.execute('mutation($input: CreateThingInput!) { createThing(input: $input) { success } }', variables: { "input" => { "name" => 1 } }).to_h
```

Here's what it prints out now: 

```
LITERAL VALUE ERROR
{"errors"=>
  [{"message"=>
     "Argument 'name' on InputObject 'CreateThingInput' has an invalid value (1). Expected type 'String!'.",
    "locations"=>[{"line"=>1, "column"=>31}],
    "path"=>["mutation", "createThing", "input", "name"],
    "extensions"=>
     {"code"=>"argumentLiteralsIncompatible",
      "typeName"=>"InputObject",
      "argumentName"=>"name"}}]}


VARIABLE VALUE ERROR
{"errors"=>
  [{"message"=>
     "Variable $input of type CreateThingInput! was provided invalid value for name (Could not coerce value 1 to String)",
    "locations"=>[{"line"=>1, "column"=>10}],
    "extensions"=>
     {"value"=>{"name"=>1},
      "problems"=>
       [{"path"=>["name"],
         "explanation"=>"Could not coerce value 1 to String"}]}}]}
```

@bejczib, I'm sorry you don't like that behavior! I don't plan to work further on it. If you want to change the behavior of your system, you might be able to modify the behavior of the parent class, eg: 

```ruby
class GraphQL::StaticValidation::Error 
  # override this to remove `"path"`
  def to_h 
    h = super 
    h.delete("path")
    h 
  end 
end 
```

I think that would cause returned errors to _not_ have `"path"` in them! If you try that (or something else) and run into a problem, please open a new issue.

**Closed by rmosolgo** 2020-03-20 14:05 UTC
