### ISSUE TITLE
Returning lots of objects is slow

### ISSUE THREAD

**Issue by lovitt** [rmosolgo/graphql-ruby#861] opened 2017-07-31 21:41 UTC
We're seeing some performance issues with a certain field that returns a lot of data. To better understand how GraphQL performance depends on the size of the response, we wrote a benchmark script that uses the GraphQL gem to query for increasingly large lists of objects at once:

https://gist.github.com/lovitt/effa205b876d9a9b86ee58399cceaf31

All test data is pre-generated and in memory, so the script should only be measuring the overhead of the GraphQL system itself — the time it takes to resolve each of the fields, check the raw value against the expected type, etc., and build the response (i.e., not time to pull data out of some database). All returned objects are of the same type, and all 10 of its fields are requested in the query.

Here are the results on my OS X dev machine:

```
Calculating -------------------------------------
Querying for 10 objects - all fields                   
                        225.168  (±26.6%) i/s -    952.000  in   5.041098s
Querying for 100 objects - all fields                  
                         29.132  (±24.0%) i/s -    130.000  in   5.038850s
Querying for 1000 objects - all fields                 
                          2.713  (± 0.0%) i/s -     14.000  in   5.346691s
Querying for 10000 objects - all fields                
                          0.262  (± 0.0%) i/s -      2.000  in   7.654611s

Comparison:
Querying for 10 objects - all fields                   :      225.2 i/s
Querying for 100 objects - all fields                  :       29.1 i/s - 7.73x  slower
Querying for 1000 objects - all fields                 :        2.7 i/s - 82.99x  slower
Querying for 10000 objects - all fields                :        0.3 i/s - 858.20x  slower
```

For this particular test schema and object type, there seems to be around ~1.8ms of overhead introduced for every object in the response. Do these numbers sound right? Are these performance characteristics about what we should expect...?

**Comment by rmosolgo** [comment] 2017-08-01 16:10
Hi again, thanks again for such a great benchmark! 

To be honest, I don't find these numbers surprising. This range of "small" to "giant" matches what I've seen in other profiling exercises. 

I forked your benchmark and added a couple of my favorite tools, `ruby-prof` and `memory_profiler`, then uploaded the results: 

https://gist.github.com/rmosolgo/b7c1af9ef6733c648156cb476c6eb700

`ruby-prof` says where _time_ was spent, which methods: 

```
 %self      total      self      wait     child     calls  name
 11.47      3.102     1.396     0.000     1.706   730177  *Class#new
  7.19      2.501     0.875     0.000     1.627   410000   GraphQL::Query::Context::FieldResolutionContext#spawn
  6.94      0.845     0.845     0.000     0.000  4340091   Module#===
  6.18      0.751     0.751     0.000     0.000   410001   GraphQL::Query::Context::FieldResolutionContext#initialize
  3.72      0.653     0.453     0.000     0.200  1630008   Kernel#===
  3.02      0.368     0.368     0.000     0.000  1840034   Kernel#is_a?
  2.68      0.691     0.326     0.000     0.365   310000   GraphQL::Execution::FieldResult#value=
  2.05      0.940     0.249     0.000     0.691   310000   GraphQL::Execution::FieldResult#initialize
  1.64      0.200     0.200     0.000     0.000  1120007   BasicObject#==
  1.59      0.390     0.194     0.000     0.196   120000   <Object::GraphQL::ScalarType>#coerce_result
  1.30      0.201     0.159     0.000     0.043   100001   GraphQL::Query#arguments_for
  1.23      0.149     0.149     0.000     0.000   880063   Kernel#nil?
  1.01      0.122     0.122     0.000     0.000   120000   String#encode
```

A lot of time spent in `#new` and `#initialize` (and `#spawn`, which is a GraphQL method for allocating new `context`s). So I think the key to improving runtime is to decrease the number of objects allocated!

And memory_profiler says where _memory_ was spent, what kind of objects: 

```

allocated objects by class
-----------------------------------
   1460155  Hash
    600350  Array
    410001  GraphQL::Query::Context::FieldResolutionContext
    310000  GraphQL::Execution::FieldResult
    120032  String
     30003  Enumerator
     10001  GraphQL::Execution::SelectionResult
       145  Proc
        23  GraphQL::InternalRepresentation::Node
        21  GraphQL::Language::Visitor::NodeVisitor
        12  GraphQL::InternalRepresentation::Scope
         7  GraphQL::StaticValidation::TypeStack::EnterWithStrategy
         7  GraphQL::StaticValidation::TypeStack::LeaveWithStrategy
         5  Set
         4  Method
         2  GraphQL::Filter
         2  GraphQL::InternalRepresentation::Rewrite::VisitDefinition
         2  GraphQL::NonNullType
```

Sadly this is _not_ super surprising to me: A `FieldResolutionContext` is allocated for _every_ field in the response, so those allocations grow as the response grows. `FieldResult` and `SelectionResult` have similar usages. `Hash` and `Array` will need some special digging to see where those are allocated, so we can clean them up. (You can filter `memory_profiler` output by class, then use the "allocated objects by location" section to identify where the Arrays and Hashes are coming from.)

But the situation could _definitely_ be improved. Besides the cleanup on `Array` and `Hash`, the three `GraphQL` classes mentioned above serve very similar purposes and could probably be merged (although this is a tough refactor).

**Comment by rmosolgo** [comment] 2017-08-28 11:40
Hoping to remove some of these redundant object allocations in #923

**Comment by rmosolgo** [comment] 2017-08-28 21:09
Ran these again on d874f79 and saw some improvements. The benchmark is a good bit (~30%) faster: 

```
Querying for 10 objects - all fields                   
                        295.518  (±14.2%) i/s -      1.428k in   5.007656s
Querying for 100 objects - all fields                  
                         37.471  (±13.3%) i/s -    180.000  in   5.054762s
Querying for 1000 objects - all fields                 
                          3.658  (± 0.0%) i/s -     18.000  in   5.016701s
Querying for 10000 objects - all fields                
                          0.335  (± 0.0%) i/s -      2.000  in   6.013074s
```

The overall memory usage is better too: 

```diff
- Total allocated: 464321016 bytes (2940816 objects)
+ Total allocated: 260320824 bytes (2000815 objects)
```

The method profile shows a lot less time in `.new` and `#initialize`, but now much more in `===`: 

```
 %self      total      self      wait     child     calls  name
  9.52      1.119     1.119     0.000     0.000  6520102   Module#===
  8.69      1.303     1.021     0.000     0.283   410001   GraphQL::Query::Context::FieldResolutionContext#initialize
  5.61      1.963     0.659     0.000     1.304   410176  *Class#new
  4.04      0.678     0.475     0.000     0.203  1750009   Kernel#===
  3.96      2.428     0.465     0.000     1.962   410001   GraphQL::Query::Context::SharedMethods#spawn_child
  3.17      0.939     0.373     0.000     0.566   420001   GraphQL::Query::Context::FieldResolutionContext#value=
  2.49      0.293     0.293     0.000     0.000  1530036   Kernel#is_a?
  2.25      0.264     0.264     0.000     0.000  1660009   BasicObject#==
  1.62      0.190     0.190     0.000     0.000   610003   GraphQL::Query::Context::SharedMethods#invalid_null?
  1.48      0.399     0.174     0.000     0.224   120000   <Object::GraphQL::ScalarType>#coerce_result
  1.27      0.150     0.150     0.000     0.000   120000   String#encode
  1.27      0.149     0.149     0.000     0.000   880063   Kernel#nil?
```

So I'll see if I can avoid some of those!

**Comment by rmosolgo** [comment] 2017-08-28 21:41
A bit better after fc50dfe2, although the actual benchmark didn't change much: 

```
 %self      total      self      wait     child     calls  name
  8.73      1.263     0.979     0.000     0.284   410001   GraphQL::Query::Context::FieldResolutionContext#initialize
  7.85      0.881     0.881     0.000     0.000  4930099   Module#===
  6.09      1.948     0.684     0.000     1.264   410176  *Class#new
  4.30      2.429     0.482     0.000     1.947   410001   GraphQL::Query::Context::SharedMethods#spawn_child
  4.02      0.651     0.451     0.000     0.200  1750009   Kernel#===
  3.32      0.931     0.372     0.000     0.559   420001   GraphQL::Query::Context::FieldResolutionContext#value=
  2.58      0.289     0.289     0.000     0.000  1530036   Kernel#is_a?
  2.34      0.263     0.263     0.000     0.000  1660009   BasicObject#==
  1.71      0.192     0.192     0.000     0.000   610003   GraphQL::Query::Context::SharedMethods#invalid_null?
  1.56      0.354     0.175     0.000     0.179   120000   <Object::GraphQL::ScalarType>#coerce_result
  1.33      0.149     0.149     0.000     0.000   880063   Kernel#nil?
```

All in all, it's a nice reduction of overhead!

**Comment by volkanunsal** [comment] 2017-10-26 19:52
@rmosolgo Would is make sense to create a small number of `FieldResolutionContext`s in a pool and reuse them somehow?

**Comment by lovitt** [comment] 2017-12-12 16:12
Hi @rmosolgo, I'm sorry for the long delay. I really appreciate your taking the time to look at this benchmark and make these optimizations. 

Strangely, I'm not able to see any meaningful difference in runtimes when I run my original benchmark script against `graphql-ruby` 1.6.6 (the version I initially benchmarked) versus 1.7.7 (the current version). This is on my OS X dev machine, FWIW. But the optimizations make sense and I'm glad you are seeing a speedup in your tests.

**Comment by Pepan** [comment] 2018-06-13 09:10
Any progress on this?

**Comment by rmosolgo** [comment] 2018-06-13 13:20
Hey @pepan, it's been almost a year since this was opened, so if you're on the latest version of graphql-ruby, feel free to post some benchmarking info!

**Comment by JoshCheek** [comment] 2018-06-29 15:03
Note that you could probably check the types on the first hand full of results and then periodically sample them for further type varification. Probably a big perf improvement with low probability of missing a regression. Perhaps let users opt into it, eg for their prod env.

**Comment by joshjcarrier** [comment] 2018-07-04 04:20
Maybe this mini benchmark helps -- I'm assuming its related to the number of unique field contexts involved.

For the largest execution time, a flamegraph shows 
* 28% in `graphql-1.8.4/lib/graphql/query/context.rb:197:in `GraphQL::Query::Context::FieldResolutionContext#initialize'`
* 17% GC time
* 15% `concurrent-ruby-1.0.5/lib/concurrent/collection/map/mri_map_backend.rb:21:in Concurrent::Collection::MriMapBackend#compute_if_absent` as part of `graphql-1.8.4/lib/graphql/schema.rb:601:in GraphQL::Schema#lazy_method_name`

[flamegraph.html.zip](https://github.com/rmosolgo/graphql-ruby/files/2161828/flamegraph.html.zip)

Hope this helps!

```log
> ruby graph.rb
contexts
===================
    1                =>   0.030000   0.000000   0.030000 (  0.030921)
 5000                =>   0.110000   0.010000   0.120000 (  0.113914)
    5 x 10 x 10 x 10 =>   0.130000   0.000000   0.130000 (  0.133547)
   20 x 40 x 40 x 30 =>   0.290000   0.000000   0.290000 (  0.288941)
```

### graph.rb
```ruby
require 'graphql'
require 'benchmark'

NumberType = GraphQL::ObjectType.define do
  name "Number"

  field :one, types.Int do
    resolve ->(_,_,_) { 1 }
  end

  field :two, types.Int do
    resolve ->(_,_,_) { 2 }
  end

  field :three, types.Int do
    resolve ->(_,_,_) { 3 }
  end

  field :numbers, types[NumberType] do
    argument :count, types.Int
    resolve ->(object, args, ctx) {
      1..args[:count]
    }
  end
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :integers, types[types.Int] do
    argument :count, types.Int
    resolve ->(object, args, ctx) {
      1..args[:count]
    }
  end

  field :numbers, types[NumberType] do
    argument :count, types.Int
    resolve ->(object, args, ctx) {
      1..args[:count]
    }
  end
end

MySchema = GraphQL::Schema.define do
  query QueryType
end

# make sure all schema is loaded before measuring
MySchema.execute(<<-GQL
  query test {
    __typename
    numbers(count: 1) {
      one
    }
  }
  GQL
    )

result_1_unique_context = Benchmark.measure {
  MySchema.execute(<<-GQL
query test {
  integers(count: 5000)
}
GQL
  ).to_h
}

result_5000_unique_contexts = Benchmark.measure {
  MySchema.execute(<<-GQL
query test {
  numbers(count: 5000) {
    one
  }
}
GQL
  ).to_h
}

result_5000_unique_nested_contexts = Benchmark.measure {
  MySchema.execute(<<-GQL
query test {
  numbers(count: 5) {
    numbers(count: 10) {
      numbers(count: 10) {
        numbers(count: 10) {
          one
        }
      }
    }
  }
}
GQL
  ).to_h
}

result_960_000_unique_nested_contexts = Benchmark.measure {
  MySchema.execute(<<-GQL
query test {
  numbers(count: 5) {
    one
    two
    three
    numbers(count: 10) {
      one
      two
      three
      numbers(count: 10) {
        one
        two
        three
        numbers(count: 10) {
          one
          two
          three
        }
      }
    }
  }
}
GQL
  ).to_h
}

puts "contexts\n==================="
puts "    1                => #{result_1_unique_context}"
puts " 5000                => #{result_5000_unique_contexts}"
puts "    5 x 10 x 10 x 10 => #{result_5000_unique_nested_contexts}"
puts "   20 x 40 x 40 x 30 => #{result_960_000_unique_nested_contexts}"
```

**Comment by rmosolgo** [comment] 2018-07-04 19:03
Thanks for the detailed benchmark! That's my understanding too, that the sheer number of objects allocated causes a lot of overhead. 

Currently I'm pretty focused landing the finishing touches to the built-in authorization stuff, and getting that deployed at GitHub, but after that, my focus will be on improving runtime performance. (It's also a GitHub priority!)

I'm pretty stumped about how to reduce that, because those objects _seem_ really necessary. You need something to whole the runtime path, for example (which includes list indexes, unlike the static path), and something to hold on to promises while they're still pending. 

My first order of business before hacking on the runtime is to read up a bit, I got a couple of books with my learning budget: [Language Implementation Patterns](https://pragprog.com/book/tpdsl/language-implementation-patterns) and [Essentials of Programming Languages](http://www.eopl3.com/), so I'm hoping some proper book learnin' will help!

There _are_ some techniques I can think of from programming language optimization, like reusing frames instead of making new ones, and not allocating frames when you can avoid it. I wonder if something like that will come in handy.

**Comment by rmosolgo** [comment] 2018-09-06 14:45
Hi, just wanted to share an update. I'm working on a new runtime over at #1394. Instead of eagerly `dup`ing all the objects for different fields, it duplicates them only when needed. (Namely, when requested by `extras [...]` or when fields return promises.) So I'm optimistic that it will improve runtime performance a lot. It's not quite ready yet though. Feel free to keep an eye on that issue if you're interested.

**Comment by Pepan** [comment] 2018-09-06 14:49
Can we test it somehow on our system to for example report performance change, errors etc...

**Comment by rmosolgo** [comment] 2018-09-06 14:55
Sure, feel free to pull the branch! It's not documented at all, but you can see the changes to the test fixtures for how it can be installed. It doesn't support all runtime features yet, you can see the checklist in the PR description.

**Comment by rmosolgo** [comment] 2018-09-25 17:46
I've migrated the benchmark above to the class-based schema so that I can try it with the new interpreter: https://gist.github.com/rmosolgo/eda7d1023cf0b096d52da6ba387b2785

Nothing to report on yet, but I wanted to share that I'm hacking away at it!

**Comment by rmosolgo** [comment] 2019-01-29 13:08
I came back here to double-check my benchmark results and found I never posted them 🙈 ! So I ran them again. 

## Before 

```
Calculating -------------------------------------
Querying for 10 objects - all fields
                        163.645  (±16.5%) i/s -    768.000  in   5.015027s
Querying for 100 objects - all fields
                         18.821  (±15.9%) i/s -     86.000  in   5.032493s
Querying for 1000 objects - all fields
                          1.807  (± 0.0%) i/s -     10.000  in   5.730450s
Querying for 10000 objects - all fields
                          0.163  (± 0.0%) i/s -      1.000  in   6.127659s
```

## After 

Using features on `master`: 

```diff 
+     use GraphQL::Analysis::AST
+     use GraphQL::Execution::Interpreter
```

```
Calculating -------------------------------------
Querying for 10 objects - all fields
                        251.892  (±12.3%) i/s -      1.224k in   5.007991s
Querying for 100 objects - all fields
                         29.337  (± 6.8%) i/s -    146.000  in   5.019815s
Querying for 1000 objects - all fields
                          2.954  (± 0.0%) i/s -     15.000  in   5.098905s
Querying for 10000 objects - all fields
                          0.268  (± 0.0%) i/s -      2.000  in   7.507030s
```

So, it seems about 50% faster.

**Comment by raysuelzer** [comment] 2019-06-25 02:49
While this is faster, it unfortunately seems like the bottle neck is probably Ruby itself.  I'm not well versed in Ruby, I come from a different background, but 5 seconds for 1000 objects is painfully slow.  Is it fair to assume that there isn't going to be any realistic chance of squeezing more performance out of this library?

**Comment by rmosolgo** [comment] 2019-06-25 14:29
> 5 seconds for 1000 objects

That's not how I interpret the benchmark I posted above. Here's the line I interpret: 

```
Querying for 1000 objects - all fields
                          2.954  (± 0.0%) i/s -     15.000  in   5.098905s
```

15 iterations in 5.09 seconds would 1000 objects in 333ms (not 5s).  Does that interpretation seem right to you?

>  isn't going to be any realistic chance

I think that's right. I don't feel too bad about it: although 333ms for 1000 Ruby objects _seems_ slow, it might not be so bad when compared to the real alternative, several calls to REST API. 

There _might_ be a few drops of performance to squeeze out still, basically looking at parts of GraphQL that you can _bypass_ in certain cases. For example, if you're running static queries that are validated at application boot, then you could run `validate: false`. There might also be cases where you could _skip_ scalar coercion, if you know that it's going to be a no-op (eg, turning Ruby strings into GraphQL strings, recognizing that special case).

**Comment by raysuelzer** [comment] 2019-06-25 18:24
Thank you for the response, I appreciate it.  I was not reading the results correctly. 

I haven't really dug into the source code here to do any real benchmarking, but in our application it is taking 9-10 seconds to return about 1000 objects with only a few scalar fields selected.  We made major performance gains by eliminating all the N+1 queries, but it seems like 99% the time is currently spent in the #execute phase.  Using the new interperter did not make any perceivable difference in execution time. Perhaps, I am not using it correctly?  But, according to my traces it is using the new interpreter when I enable it. 

It seems like CPU is the bottleneck here, so I'd imagine that adding some multi-threading may help here? 
The other thing that may possibly be improved is to somehow memoize certain resolve operations. 

For example if I have the following query.  

```
{
  getPosts {
     id
     title
     author {
      id
      name
    }
  }
}
```

Instead of just caching the result of 'author' once, the interpreter seems to evaluate it for each node in the AST.  Which means that it ends up trying resolve fields for the same author that have already been resolved before. 

I'm not sure if what I am saying makes sense or not, but it seems like the interpreter should have a way of knowing if it has walked the `author` tree before based upon the ID or a hash of the input `object` passed to the `author_type` and use that result instead of rebuilding it over and over again.

I appreciate your work on this.

**Comment by rmosolgo** [comment] 2019-06-25 19:03
I haven't looked into optimizations like that because it's not a bottleneck for my application. (For us, it's application logic and IO.) How about trying some Ruby profilers to make sure we're hunting the right target? Here are two I'm familiar with: 

- https://github.com/SamSaffron/memory_profiler/
- https://github.com/ruby-prof/ruby-prof

The output of those profilers can be a bit ... dense ... but if you want to interpret it together, I'd be happy to take a look at the output. Just open another issue and share your benchmark code and the output of those. 

Here's some example code about how I do that when working on this gem: 

https://github.com/rmosolgo/graphql-ruby/blob/1a21f665554a00c822b8f5212b2900e64ec17a91/benchmark/run.rb#L44-L52

https://github.com/rmosolgo/graphql-ruby/blob/1a21f665554a00c822b8f5212b2900e64ec17a91/benchmark/run.rb#L73-L77

(Those scripts write to stdout, so I write the result to a file, for example `bundle exec rake:benchmark > before_profile.txt`.)

**Comment by rmosolgo** [comment] 2019-07-10 13:29
I don't think there's specific work to be done in this area right now (except for the discussion in #2352) , so I'm closing this.

**Closed by rmosolgo** 2019-07-10 13:29 UTC
