### ISSUE TITLE
required argument when invisible

### ISSUE THREAD

**Issue by nekogami** [rmosolgo/graphql-ruby#2392] opened 2019-07-23 09:43 UTC
graphql-ruby: 1.9.4
ruby: 2.6.3p62

Hi,
First thank you for this gem, reaaaally appreciate it :D (specially since it went class based :3 )

It's not really a bug but a question on a custom behavior allowed by graphql-ruby
Context:
I created a custom argument class that defines the return of the visible? method according to a custom_user I store in the context.

So far so good, depending on the custom_user in the context, the generated schema does include or exclude the argument (When I look at it through my client at least).

What I noticed though is that, even though the argument is not visible, if specified as required, a user who is cannot see it will still get the error that it's a required argument.

Should the requirement of an invisible field also become false ?
The method visible? being a specific implementation of the graphql-ruby library (as for as I understand at least), I was wondering what your (@rmosolgo and the community) was on that.

That or I did something wrong and it's already supposed to work ... In that case, help ? :D

**Comment by rmosolgo** [comment] 2019-07-23 14:51
Yes, this is a bug, sorry! Duplicate of https://github.com/rmosolgo/graphql-ruby/issues/1439

**Closed by rmosolgo** 2019-07-23 14:51 UTC

**Comment by rmosolgo** [comment] 2019-07-23 15:15
Fixed on master, feel free to give it a try!

**Comment by nekogami** [comment] 2019-07-24 09:24
Wow, that was quick ! Thank you
