### ISSUE TITLE
Type should be hidden if none of its fields are visible

### ISSUE THREAD

**Issue by xuorig** [rmosolgo/graphql-ruby#954] opened 2017-09-15 13:31 UTC
We can get into this scenario:

https://github.com/xuorig/graphql-ruby/blame/master/spec/graphql/schema/printer_spec.rb#L491-L493

Which is invalid 🤷‍♂️ 

Related https://github.com/rmosolgo/graphql-ruby/pull/919

**Comment by rmosolgo** [comment] 2020-02-13 17:37
Closing as duplicate of #2645, which has more detail on the issue.

**Closed by rmosolgo** 2020-02-13 17:37 UTC
