### ISSUE TITLE
json scalar type

### ISSUE THREAD

**Issue by huan-ji** [rmosolgo/graphql-ruby#146] opened 2016-05-03 18:38 UTC
Is it possible to add a json scalar type  to avoid having to send raw json as a string? That way in a JS web environment it won't be necessary to JSON.parse the string data.

**Comment by rmosolgo** [comment] 2016-05-03 18:44
Yes, you can define custom scalars. 

There's an example in the ScalarType docs: http://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/ScalarType

and one in the spec: https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/scalar_type_spec.rb

How does that look?

**Comment by DomKM** [comment] 2016-05-20 05:22
@rmosolgo How do you use a custom scalar type as a mutation input field? 

```ruby
JsonType = GraphQL::ScalarType.define do
  name "JSON"
  coerce_input -> (x) { JSON.parse(x) }
  coerce_result -> (x) { JSON.dump(x) }
end
```

```ruby
input_field :whatever, JsonType
```

The above code is causing mutation input to be wrapped in `GraphQL::Query::Arguments`.

**Comment by rmosolgo** [comment] 2016-05-20 13:46
Ohh that sounds like a bug in Query::Arguments -- I think it assumes all ruby hashes are meant to represent InputObjectTypes, but now it's possible that that's not the case! 

As a workaround you can call `Arguments#to_h` to get a plain hash version of that object.

**Comment by zamith** [comment] 2016-09-01 23:47
I tried this on an input type argument to be used in a relay mutation, and I keep getting:

```
Argument '<argument-name>' on InputObject 'SomethingInput' has an invalid value
```

The way I'm writing the mutation is:

```
mutation {
   createGroupConsultation(input: {something: {argument-name: {other_thing: 2}, other_argument: 1}}) {
    result
  }
}
```

Arguments of other types work just fine. Hope this is clear enough, as I'm also trying to figure out want went wrong, but as far as I can tell when getting [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/literal_validator.rb#L43), the `value.value` is `#<GraphQL::Language::Nodes::InputObject:0x007fc75ba419b8 @arguments=[], @col=57, @line=2>` and `field.type` is scalar, which makes the validation return false.

I suspect it might be the way I'm passing the objects in, but not sure.

**Comment by zamith** [comment] 2016-09-02 16:10
I was able to fix this by sending the arguments as strings. 

```
mutation {
   createGroupConsultation(input: {something: {argument-name: "{\"other_thing\": 2}", other_argument: 1}}) {
    result
  }
}
```

Is this the intended behaviour?

**Comment by rmosolgo** [comment] 2016-09-02 23:10
> Is this the intended behaviour?

Yes -- for the JsonType described above, the data must be sent as string. If the data is given as GraphQL arguments, GraphQL will try to validate them!

**Comment by chrise86** [comment] 2016-10-03 11:24
My arguments are still getting wrapped in `GraphQL::Query::Arguments`. On the client I am calling `JSON.stringify(object)`. What am I doing wrong?

**Comment by rmosolgo** [comment] 2016-10-12 02:00
Taking a crack at fixing this here: https://github.com/rmosolgo/graphql-ruby/pull/304

After that, `argument :json, JSONScalar` will be a plain hash instead of a `Query::Arguments`

**Comment by rmosolgo** [comment] 2016-10-14 01:59
That fix was merged into 0.19.3, please let me know if you find the argument bug again!

**Closed by rmosolgo** 2016-10-14 01:59 UTC

**Comment by bwinterling** [comment] 2017-10-10 20:19
Just wanted to add a comment here in case it helps other folks that find their way here.  Using <schema class name>.execute(query_string) to test my schema, I was getting a parse error.

`{"errors"=>[{"message"=>"Parse error on \":\" (STRING) at [1, 44]", "locations"=>[{"line"=>1, "column"=>44}]}]}` or 
`{"errors"=>[{"message"=>"Parse error on \"super\" (STRING) at [1, 39]", "locations"=>[{"line"=>1, "column"=>39}]}]}`

Don't forget to double escape the JSON string in your query string.

For example:
```
query_string = <<~QUERY
  mutation {
    updateForm(
      id: #{form.id},
      data: "{ \\"super\\": \\"special\\" }"
    ) { data }
  }
QUERY   
```

**Comment by jturkel** [comment] 2018-04-05 17:35
@rmosolgo - Is supporting non-string encoded custom JSON scalars totally off the table? We've hit a use case where they could be useful. graphql.js supports them via [graphql-type-json](https://github.com/taion/graphql-type-json) so it would be consistent with the reference GraphQL implementation :)

**Comment by rmosolgo** [comment] 2018-04-05 17:38
I'm open to it!
