### ISSUE TITLE
Bare-word names are parsing as strings

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#1772] opened 2018-08-14 15:27 UTC
Consider a query like
```
{
  node(id: garbage) {
    id
  }
}
```

GraphiQL red-underlines this as invalid syntax (since IDs are strings and should be quoted). On graphql-js similarly you get back a top-level error "Expected type ID!, found garbage".

In graphql-ruby (1.8.7) it executes the query with `id` given the value of `"garbage"`. As far as I can tell this is not spec-compliant.

cc  @bernardoamc @swalkinshaw

**Comment by rmosolgo** [comment] 2018-08-14 15:34
yes, seems wrong 😆

**Comment by xuorig** [comment] 2018-08-14 16:20
It's a feature, not a bug 😆

**Comment by cjoudrey** [comment] 2018-08-14 16:44
Probably related, but this also parses correctly:

```
{
  node(id:) {
    id
  }
}
```

I'll take a look later, unless someone gets to it before.

**Comment by daemonsy** [comment] 2019-06-25 13:43
I made a PR for another issue that parses `# comment` as an empty document (should raise error) 
https://github.com/rmosolgo/graphql-ruby/pull/2344

Long story short, I got racc/ragel/colm setup, would like to give this a shot.

**Comment by daemonsy** [comment] 2019-06-27 04:49
This was pretty fun, took quite a bit of head banging to spot the subtle issue. @cjoudrey 

https://github.com/rmosolgo/graphql-ruby/pull/2344/commits/f2191b33e29272b326ef30183e967b8859873b9b

**Comment by rmosolgo** [comment] 2019-06-27 13:38
What a find! 🍻

**Comment by rmosolgo** [comment] 2019-07-10 13:57
Same as #2371, I think

**Comment by daemonsy** [comment] 2019-07-10 14:18
I think `garbage` is still parsed correctly as an enum value when the spec might specify that it must be all caps. Let me check that!

**Comment by daemonsy** [comment] 2019-07-10 14:20
Related: https://github.com/rmosolgo/graphql-ruby/issues/2371

**Comment by rmosolgo** [comment] 2019-10-23 14:55
it looks like this is fixed in the latest version: 

```ruby 
# test.rb
require "graphql"

class Query < GraphQL::Schema::Object
  field :str, String, null: false do
    argument :input, String, required: true
  end

  def str(input:)
    input
  end
end

class Schema < GraphQL::Schema
  query(Query)
end

p Schema.execute('{ str(input: "abc") }')
p Schema.execute('{ str(input: abc) }')
```

```
$ ruby test.rb
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"str"=>"abc"}}>
#<GraphQL::Query::Result @query=... @to_h={"errors"=>[{"message"=>"Argument 'input' on Field 'str' has an invalid value (abc). Expected type 'String!'.", "locations"=>[{"line"=>1, "column"=>3}], "path"=>["query", "str", "input"], "extensions"=>{"code"=>"argumentLiteralsIncompatible", "typeName"=>"Field", "argumentName"=>"input"}}]}>
```

**Closed by rmosolgo** 2019-10-23 14:55 UTC
