### ISSUE TITLE
Guide: Arguments

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#3115] opened 2020-08-26 21:17 UTC
I've come across a situation where `prepare` is run twice.

I'd like to have a hook for an argument that will always return the raw value of the argument

e.g.

if I have a mutation as such:

```graphql
mutation {
  updateUser(id: 'example', input: { locationStrings: ['San Francisco, CA', 'New York, NY'] }) {
    user {
      locations {
        id
        long
        lat
      }
    }
  }
}
```

```rb
# frozen_string_literal: true

module Mutations
  class UpdateUser < Mutations::BaseMutation
    class UpdateUserInput < Types::BaseInputObject
      argument :location_strings, [String], required: false, as: :locations, default_value: [], prepare: ->(location_strings, ctx) {
         Location.where(location_string: location_strings)
      }

      def prepare
        to_h
      end
    end

    argument :id, ID, required: true
    argument :input, UpdateUserInput, required: true

    field :user, Types::UserType, null: true

    def resolve(id:, input:)
      user = User.find_by!(uuid: id)

      authorize! user, to: :update?

      user.update!(input)

      {
        user: user
      }
    end
  end
end
```

in some cases I've seen the resolver do the following:

1. mutation runs prepare statements for input
2. mutation runs prepare statements for input again
3. resolve runs

is there a way you'd suggest dealing with something like this @rmosolgo ?

**Comment by rmosolgo** [comment] 2021-02-23 15:16
duplicate of https://github.com/rmosolgo/graphql-ruby/issues/1376 

No, I don't know a way to get the "unprepared" argument value when `prepare:` is given. After prepare is called, the argument value is replaced with the result of the `prepare` hook. The only other way to inspect the arguments would be `extras: [:ast_node]`, but that would give you raw AST (without coercion, variable inlining, etc).

**Closed by rmosolgo** 2021-02-23 15:16 UTC
