### ISSUE TITLE
Question: best way to catch ActiveRecord::StatementInvalid error in field resolve

### ISSUE THREAD

**Issue by geneeblack** [rmosolgo/graphql-ruby#1131] opened 2017-11-26 18:57 UTC
I am sending an invalid AR query to a list resolve on a nested list type field and don't seem to be able to catch the ActiveRecord::StatementInvalid error anywhere in my code. I have an error handling wrapper enabled on my schema but it never seems to bubble up to it unless I materialize the query before sending it on down the chain.

The code where the error is initiated is at
https://github.com/rmosolgo/graphql-ruby/blob/v1.7.6/lib/graphql/execution/execute.rb#L193

I am intentionally sending an invalid sort predicate on the query to test error handling. 

Is there a way that you know of that I can catch the error originating from the code above without materializing my query object before returning it from the field resolve?  

As of now, to work around the issue, I am running the query with obj.limit(0).to_a to realize it in my resolve method and catch the error if it occurs. But this causes an additional, albeit slight,  hit on the database since it is then also materialized later after the return from the resolve. Since it is a nested field with its own limit, this slight overhead is multiplied when running the n+1 queries for the limited nested records.

**Comment by rmosolgo** [comment] 2017-11-28 00:32
I think I see what you mean, the error is caused by GraphQL internals, where calling `each` causes the AR::Relation to execute its SQL. 

> intentionally sending an invalid sort predicate

Well... there's your problem 😆 

Really though, the best bet is to prevent these errors from happening. For example, use a GraphQL enum type for your sort options, so that only a specific set of inputs is supported.

If you want to investigate further options, could you post the stack trace of the errors? That might suggest some spots where error handling could be added.

**Comment by geneeblack** [comment] 2017-11-28 11:32
Yeah, I'd originally thought about using an enum, but since the end user can dynamically include nested tables via associations based on their query selections it wasn't feasible. And building out the enum to include all possible nested relationships and their columns would be exhaustive (many levels of nesting). At this point I'm simply looking for a way to gracefully handle the error and return the sql statement. 

I have a schema level resolve error handler wrapper enabled using batchql-errors, but it doesn't catch the error. Not surprisingly since I've been unable to catch it directly in my resolve or my resolve wrapper either (since the query isn't materialized until later). It just eventually bubbles out to the controller. I could catch it in the controller, which I should probably handle anyway, given the possibility that an error could 'leak' around the error handling that I have established as resolve wrappers and it appears to be the only user code that I have access to handle the error. 

Unless there is a way to hook into graphql at another point.

Here is the stack trace with silencers disabled.

      ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'badcolumn_id' in 'order clause'
      /gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
      /gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
      /gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
      /gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
      /gems/activesupport-3.2.22.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
      /gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/active_record.rb:67:in `log_with_newrelic_instrumentation'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `exec_query'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `select'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
      /gems/activerecord-3.2.22.8/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
      /gems/activerecord-3.2.22.8/lib/active_record/relation/finder_methods.rb:259:in `construct_limited_ids_condition'
      /gems/activerecord-3.2.22.8/lib/active_record/relation/finder_methods.rb:243:in `apply_join_dependency'
      /gems/activerecord-3.2.22.8/lib/active_record/relation/finder_methods.rb:232:in `construct_relation_for_association_find'
      /gems/activerecord-3.2.22.8/lib/active_record/relation/finder_methods.rb:211:in `find_with_associations'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:171:in `exec_queries'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:160:in `block in to_a'
      /gems/activerecord-3.2.22.8/lib/active_record/explain.rb:41:in `logging_query_plan'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:159:in `to_a'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:189:in `exec_queries'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:160:in `block in to_a'
      /gems/activerecord-3.2.22.8/lib/active_record/explain.rb:41:in `logging_query_plan'
      /gems/activerecord-3.2.22.8/lib/active_record/relation.rb:159:in `to_a'
      /gems/activerecord-3.2.22.8/lib/active_record/relation/delegation.rb:6:in `each'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:193:in `resolve_value'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:156:in `continue_resolve_field'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:130:in `resolve_field'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:72:in `block (2 levels) in resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `block in trace'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:70:in `call_tracers'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `trace'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:64:in `each'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:64:in `resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:219:in `resolve_value'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:156:in `continue_resolve_field'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:130:in `resolve_field'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:72:in `block (2 levels) in resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `block in trace'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:70:in `call_tracers'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `trace'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:64:in `each'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:64:in `resolve_selection'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `block in trace'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:70:in `call_tracers'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `trace'
      /gems/graphql-1.7.6/lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:108:in `begin_query'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:80:in `map'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:185:in `with_instrumentation'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `block in trace'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:70:in `call_tracers'
      /gems/graphql-1.7.6/lib/graphql/tracing.rb:56:in `trace'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
      /gems/graphql-1.7.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
      /gems/graphql-1.7.6/lib/graphql/schema.rb:299:in `block in multiplex'
      /gems/graphql-1.7.6/lib/graphql/schema.rb:606:in `with_definition_error_check'
      /gems/graphql-1.7.6/lib/graphql/schema.rb:298:in `multiplex'
      /gems/graphql-1.7.6/lib/graphql/schema.rb:275:in `execute'
      app/controllers/graphql_controller.rb:19:in `execute'

**Comment by geneeblack** [comment] 2017-11-28 12:02
BTW, I did move my testing statement obj.limit(0).to_a to a higher level resolve which assembles most of the query predicates in use and builds out the initial selection query so I don't have to run the statement tests at the lower level nested relation leafs (where it is adding optional limits and paging predicates). Given that is much less costly, I am satisfied with doing it that way unless you have any further guidance on catching the error via graphql. 

Thanks for your time in looking at this. I wouldn't consider it a priority of you don't already have a ready built solution for catching late materialized query errors.

**Comment by david50407** [comment] 2018-03-28 15:35
Because ActiveRecord::Relation is a lazy object, any query inside won't execute until you really request data.

This also breaks `rescue SomeActiveRecordErrors` inside field's resolve block, like `ActiveRecord::ConnectionNotEstablished` and break whole execution even using [graphql-errors](https://github.com/exAspArk/graphql-errors) to catch these error. Because graphql-errors only catch errors on value evaluation, but AR raise these error after the evaluation.

**Comment by daemonsy** [comment] 2019-07-03 12:27
Hi, closing this issue because there hasn't been activity on the question for a while. 

Feel free to reopen if there are any further queries.

**Closed by daemonsy** 2019-07-03 12:27 UTC
