### ISSUE TITLE
Multiple tracers in one schema are ignored

### ISSUE THREAD

**Issue by brendo** [rmosolgo/graphql-ruby#5044] opened 2024-07-30 10:21 UTC
**Describe the bug**

This bug almost appears to be a duplicate of https://github.com/rmosolgo/graphql-ruby/issues/4542 but this time around it's with the ActiveSupport and OpenTelemetry tracers.

```rb
module Graph
  class Schema < GraphQL::Schema
    ...
    
    trace_with GraphQL::Tracing::ActiveSupportNotificationsTrace  end
end
```

This schema, with the default [`OpenTelemetry` setup](https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/main/instrumentation/graphql#usage), sees the [OpenTelemetry tracer](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb) completely ignored as spans are not included in traces yet metrics are emitted.

If I mix and match the old tracer API, I'm able to get both working:

```rb
module Graph
  class Schema < GraphQL::Schema
    ...

    tracer GraphQL::Tracing::ActiveSupportNotificationsTracing
  end
end
```

**Versions**

`graphql`: 2.3.10
`opentelemetry-instrumentation-graphql`: 0.28.2
`rails`: 7.1.3.4

**Steps to reproduce**

The test case demonstrates the opposite to the above due to how our app is built, but I think it's still sufficient to show the bug.

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  gem "graphql", "2.3.10"
  gem 'opentelemetry-api'
  gem 'opentelemetry-common'
  gem 'opentelemetry-instrumentation-graphql'
  gem 'opentelemetry-sdk'
  gem 'rails'
end

module MultipleTracer
  class Thing < GraphQL::Schema::Object
    field :str, String

    def str; "blah"; end
  end

  class Named < GraphQL::Schema::Union
    possible_types Thing
    def self.resolve_type(obj, ctx)
      Thing
    end
  end

  class Query < GraphQL::Schema::Object
    include GraphQL::Types::Relay::HasNodeField

    field :int, Integer, null: false

    def int
      1
    end

    field :thing, Thing
    def thing; :thing; end

    field :named, Named, resolver_method: :thing
  end

  class TestSchema < GraphQL::Schema
    query(Query)

    trace_with(GraphQL::Tracing::ActiveSupportNotificationsTrace)
  end
end

# Comment from here.... 
ENV['OTEL_TRACES_EXPORTER'] = 'console'
OpenTelemetry::SDK.configure do |c|
  c.use_all('OpenTelemetry::Instrumentation::GraphQL' => { schemas: [MultipleTracer::TestSchema] })
end
# ...to here to demonstrate bug

ActiveSupport::Notifications.monotonic_subscribe("execute_query.graphql") do |name, start, finish, _message_id, data|
  puts "#{name} handled"
  puts "#{data.inspect}"
end

query = "{ int thing { str } named { ... on Thing { str } } }"
MultipleTracer::TestSchema.execute(query)
```

The console will be messy, but if you search for `execute_query.graphql handled` it will be absent. If these lines are commented out, and the command is re-run, you'll see the ActiveSupport handled messages.

```rb
ENV['OTEL_TRACES_EXPORTER'] = 'console'
OpenTelemetry::SDK.configure do |c|
  c.use_all('OpenTelemetry::Instrumentation::GraphQL' => { schemas: [MultipleTracer::TestSchema] })
end
```

```sh
$ ruby inline.rb
execute_query.graphql handled
{:query=>query ...}
```

**Expected behavior**

Both tracers should be able to emit information about the GraphQL operations. So with the above example there should be a wall of trace info, as well as the two littles lines added by the ActiveSupport subscriber.

**Actual behavior**

The span information is emitted, but nothing from the ActiveSupport subscriber.

**Comment by rmosolgo** [comment] 2024-07-30 15:45
Well, maybe it's both. Looking at your example, I realized its different than the one I encountered in the OpenTelementry test suite. My initial suggestion, adding `super` calls, actually did make your script pass for me. So I opened a PR with those changes: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1090

However, the tests aren't passing because of the problem identified in #5045 ...

**Comment by brendo** [comment] 2024-07-31 01:21
Thanks so much for the speedy response! I'll try to test that branch of open-telemetry to confirm it's working today :)

**Comment by brendo** [comment] 2024-07-31 23:44
I retested today with the newly released `opentelemetry-instrumentation-graphql (0.28.4)` and unfortunately I'm still able to reproduce the bug using the test case above ^.

**Comment by rmosolgo** [comment] 2024-08-01 14:06
Do you pass `schemas: [ ... ]` in your app's installation config? If not, I suspect wonkiness there... (Without `schemas: [ ... ]`, the OpenTelemetry stuff is added to `GraphQL::Schema`, but that might not be handled well through inheritance, which I stumbed into in #5045)

**Comment by brendo** [comment] 2024-08-01 23:48
> Do you pass `schemas: [ ... ]` in your app's installation config?

We don't actually. Nice pickup. Let me find out how I can set that in our service (the configuration of OpenTelemetry is done via another gem by default).

**Comment by rmosolgo** [comment] 2024-08-12 18:17
👋  did you find any clues about this? I'd love to get it working properly...

**Comment by brendo** [comment] 2024-08-13 00:29
Hey! Sorry, I thought I posted back. We experimented with setting the schemas via the `OTEL_RUBY_INSTRUMENTATION_GRAPHQL_CONFIG_OPTS` variable but this didn't quite work because the tracer installers expect the option to be an instance of the schema, not a string:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/f999e702430a55bc9f0fdf7b4748dc2f9b6341b8/instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/instrumentation.rb#L92-L96

I attempted some hacking to use `const_get`/`constantize` but this failed with some autoloading errors (schema hadn't been discovered yet in the boot process). I haven't had a chance to get back into looking at alternative options yet and at the moment are "making it work" by mixing the deprecated and new trace APIs.

**Comment by rmosolgo** [comment] 2024-08-16 17:51
Ok, thanks for the update. I tinkered with the original script above to try to get it to fail, but I couldn't... 

I also reopened #5045 in case that's the cause, and I pushed a fix for the issue spotted there. Could you try your app with that patch?

**Comment by rmosolgo** [comment] 2024-08-19 18:50
Oops, that issue autoclosed this one. It might fix it -- if you get a chance to try out master now that it's been merged, let me know what you find.

**Comment by brendo** [comment] 2024-08-20 01:43
> Oops, that issue autoclosed this one. It might fix it -- if you get a chance to try out master now that it's been merged, let me know what you find.

Sorry, a retest confirms the bug. Switching from `tracer GraphQL::Tracing::ActiveSupportNotificationsTracing, silence_deprecation_warning: true` to `trace_with GraphQL::Tracing::ActiveSupportNotificationsTrace` causes the trace to lose the Otel spans.

I don't know if this helps at all, but here's a screenshot from a debug which shows both modules _appear_ to be added:

![Screenshot 2024-08-20 at 11 37 06 AM](https://github.com/user-attachments/assets/d7760529-3594-4407-949b-2829abd520db)

I'm missing a lot of context, but is the problem that both modules (`OpenTelemetry::Instrumentation::GraphQL::Tracers::GraphQLTrace` and `GraphQL::Tracing::ActiveSupportNotificationsTrace`) define the same method names and because the `AS:N` is added last, it overrides the OTel module?

eg. `analyze_query`:

- [Otel](https://github.com/rmosolgo/opentelemetry-ruby-contrib/blob/64d70de5dc2ff166d4d42cd79da0e3ce73b8f2f0/instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb#L91-L93)
- [`NotificationsTrace` via AS:N](https://github.com/rmosolgo/graphql-ruby/blob/951cb16b6384adaaf832303f40b5c8ebd7a69571/lib/graphql/tracing/notifications_trace.rb#L24-L39)

**Comment by rmosolgo** [comment] 2024-08-20 14:33
If you get a chance to try master again, please let me know what you find 😅 Thanks again for your help tracking this down.

**Closed** 2024-08-20 14:33 UTC

**Comment by brendo** [comment] 2024-08-20 20:17
That did it, thank you! Really appreciate the back and forth and patience to get this one solved :)
