### ISSUE TITLE
Dataloader hangs indefinitely in transaction (Ruby >= 3.0.2)

### ISSUE THREAD

**Issue by ivanbrennan** [rmosolgo/graphql-ruby#4089] opened 2022-06-03 03:32 UTC
**Describe the bug**

Starting at Ruby 3.0.2, attempting to use Dataloader in an ActiveRecord transaction block causes execution to hang indefinitely.

**Versions**

`graphql` version: 2.0.9
Ruby: >= 3.0.2 (tested 2.7.4 through 3.1.2)
`rails`: 6.1.6

**GraphQL schema**

```ruby
# Model
class ApplicationRecord < ActiveRecord::Base
end

class Foo < ApplicationRecord
end

# Dataloader Source
class FooSource < GraphQL::Dataloader::Source
  def fetch(ids)
    records = Foo.where(id: ids).index_by(&:id)
    ids.map { |id| records[id] }
  end
end

# Boilerplate
class QueryType < GraphQL::Schema::Object
end

class Field < GraphQL::Schema::Field
  argument_class GraphQL::Schema::Argument
end

class Mutation < GraphQL::Schema::RelayClassicMutation
  argument_class GraphQL::Schema::Argument
  field_class Field
  input_object_class(
    Class.new(GraphQL::Schema::InputObject) do
      argument_class GraphQL::Schema::Argument
    end
  )
  object_class(
    Class.new(GraphQL::Schema::Object) do
      field_class Field
    end
  )
end

# Mutations
class Touch < Mutation
  field :result, String
  def resolve
    dataloader.with(FooSource).load(1).touch
    { result: "Touch finished" }
  end
end

class TransactionTouch < Mutation
  field :result, String
  def resolve
    ActiveRecord::Base.transaction do
      dataloader.with(FooSource).load(1).touch
    end
    { result: "TransactionTouch finished" }
  end
end

class MutationType < GraphQL::Schema::Object
  field :touch, mutation: Touch
  field :transaction_touch, mutation: TransactionTouch
end

# Schema
class Schema < GraphQL::Schema
  query QueryType
  mutation MutationType
  use GraphQL::Dataloader
end
```

**Steps to reproduce**

```ruby
result1 = Schema.execute("mutation { touch(input: {}) { result } }")
puts(result1.to_json)

result2 = Schema.execute("mutation { transactionTouch(input: {}) { result } }")
puts(result2.to_json)
```

**Expected behavior**

Both mutations execute successfully, printing out:
```
{"data":{"touch":{"result":"Touch finished"}}}
{"data":{"transactionTouch":{"result":"TransactionTouch finished"}}}
```

**Actual behavior**

The first mutation (`touch`) completes, but the second ('transactionTouch`) hangs indefinitely:
```
{"data":{"touch":{"result":"Touch finished"}}}
^C
```

<details>
<summary>Click to view exception backtrace</summary>

```
{"data":{"touch":{"result":"Touch finished"}}}
^C/home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `enter': Interrupt
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `block in mon_enter'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `mon_enter'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:22:in `block in synchronize'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:282:in `materialize_transactions'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:328:in `materialize_transactions'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:678:in `exec_cache'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `execute_and_clear'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec_query'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:536:in `select_prepared'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:67:in `select_all'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/querying.rb:47:in `find_by_sql'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:843:in `block in exec_queries'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:828:in `exec_queries'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:631:in `load'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:249:in `records'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation/delegation.rb:88:in `each'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/activesupport-6.1.6/lib/active_support/core_ext/enumerable.rb:58:in `index_by'
	from tmp/repro_graphql_bug.rb:11:in `fetch'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/graphql-2.0.9/lib/graphql/dataloader/source.rb:100:in `run_pending_keys'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/graphql-2.0.9/lib/graphql/dataloader.rb:269:in `each'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/graphql-2.0.9/lib/graphql/dataloader.rb:269:in `block in create_source_fiber'
	from /home/ivan/Development/odeko/api/.bundle/ruby/3.1.0/gems/graphql-2.0.9/lib/graphql/dataloader.rb:303:in `block in spawn_fiber'
```

</details>

**Additional context**

I provided a mutation example, but was able to repro in a simple query as well.

I ran into this while upgrading the Ruby version of a rails app. Dataloader worked as expected prior to Ruby 3.0.2 (specifically 2.7.4 through 3.0.1). I tested with rails 6.1.3.1 and 6.1.6 with identical results.

**Comment by rmosolgo** [comment] 2022-06-03 18:27
Wow, what a bummer! Thanks for all your work isolating and reproducing this issue. I'll take a closer look soon and see if I can find anything to address it.

**Comment by rmosolgo** [comment] 2022-07-05 01:50
Thanks again for your initial research on this. I consolidated your notes above into a single script: 

<details>
<summary>GraphQL query which uses dataloader with a transaction hangs</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "rails", "7.0.3"
  gem "graphql", "~>2.0"
  gem 'sqlite3'
end

require "active_record"

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)

ActiveRecord::Schema.define do
  create_table :foos do |table|
  end
end

# Model
class Foo < ActiveRecord::Base
end

Foo.create!

# Dataloader Source
class FooSource < GraphQL::Dataloader::Source
  def fetch(ids)
    records = Foo.where(id: ids).index_by(&:id)
    ids.map { |id| records[id] }
  end
end

# Boilerplate
class QueryType < GraphQL::Schema::Object
end

class Field < GraphQL::Schema::Field
  argument_class GraphQL::Schema::Argument
end

class Mutation < GraphQL::Schema::RelayClassicMutation
  argument_class GraphQL::Schema::Argument
  field_class Field
  input_object_class(
    Class.new(GraphQL::Schema::InputObject) do
      argument_class GraphQL::Schema::Argument
    end
  )
  object_class(
    Class.new(GraphQL::Schema::Object) do
      field_class Field
    end
  )
end

# Mutations
class Touch < Mutation
  field :result, String
  def resolve
    dataloader.with(FooSource).load(1).touch
    { result: "Touch finished" }
  end
end

class TransactionTouch < Mutation
  field :result, String
  def resolve
    ActiveRecord::Base.transaction do
      dataloader.with(FooSource).load(1).touch
    end
    { result: "TransactionTouch finished" }
  end
end

class MutationType < GraphQL::Schema::Object
  field :touch, mutation: Touch
  field :transaction_touch, mutation: TransactionTouch
end

# Schema
class Schema < GraphQL::Schema
  query QueryType
  mutation MutationType
  use GraphQL::Dataloader
end


result1 = Schema.execute("mutation { touch(input: {}) { result } }")
puts(result1.to_json)

result2 = Schema.execute("mutation { transactionTouch(input: {}) { result } }")
puts(result2.to_json)
```

</p>
</details>

But it turns out you don't even need a query, I could replicate it just with `Dataloader.with_dataloading`: 

<details>
<summary>GraphQL dataloader hangs when it's called inside a transaction</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "rails", "7.0.3"
  gem "graphql", "~>2.0"
  gem 'sqlite3'
end

require "active_record"

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)

ActiveRecord::Schema.define do
  create_table :foos do |table|
  end
end

# Model
class Foo < ActiveRecord::Base
end

Foo.create!

# Dataloader Source
class FooSource < GraphQL::Dataloader::Source
  def fetch(ids)
    records = Foo.where(id: ids).index_by(&:id)
    ids.map { |id| records[id] }
  end
end

GraphQL::Dataloader.with_dataloading do |dataloader|
  ActiveRecord::Base.transaction do
    p dataloader.with(FooSource).load(1).touch
  end
end
```

</p>

</details>


And in the end, I didn't even need GraphQL. I could cause ActiveRecord to hang by creating and resuming a fiber inside a transaction block:


<details>
<summary>Creating and resuming a fiber within a transaction doesn't work (includes backtrace)</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "rails", "7.0.3"
  gem "graphql", path: "./"
  gem 'sqlite3'
end

require "active_record"

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)

ActiveRecord::Schema.define do
  create_table :foos do |table|
  end
end

class Foo < ActiveRecord::Base
end

ActiveRecord::Base.transaction do
  load_fiber = Fiber.new do
    Foo.first
  end

  load_fiber.resume
end

# This script never finishes

# /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `enter': Interrupt
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `block in mon_enter'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:17:in `mon_enter'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:22:in `block in synchronize'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/transaction.rb:282:in `materialize_transactions'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:324:in `materialize_transactions'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:41:in `exec_query'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/querying.rb:54:in `_query_by_sql'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:941:in `block in exec_main_query'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:927:in `exec_main_query'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:913:in `block in exec_queries'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:961:in `skip_query_cache_if_necessary'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:907:in `exec_queries'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:695:in `load'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:250:in `records'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation.rb:245:in `to_ary'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation/finder_methods.rb:549:in `find_nth_with_limit'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation/finder_methods.rb:534:in `find_nth'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation/finder_methods.rb:146:in `first'
# 	from /Users/rmosolgo/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/querying.rb:22:in `first'
# 	from rails_hang.rb:29:in `block (2 levels) in <main>'

```
</p>

</details>

In light of that, I don't think I can do anything more here: Fibers don't seem to work inside Rails transactions. However, you _could_ use a transaction inside the Dataloader source, in case that helps: 


```ruby 
# Dataloader Source
class FooSource < GraphQL::Dataloader::Source
  def fetch(ids)
    ActiveRecord::Base.transaction do
      records = Foo.where(id: ids).index_by(&:id)
      ids.map { |id| records[id] }
    end
  end
end
```

You could try taking this issue to Rails, but I'm going to close this as there's not anything I can do further with GraphQL-Ruby 🙇 !

**Closed by rmosolgo** 2022-07-05 01:50 UTC

**Comment by glasses618** [comment] 2023-03-24 07:17
These PRs seem to have fixed the issue:
https://github.com/rails/rails/pull/46519
https://github.com/rails/rails/pull/46553
https://github.com/rails/rails/pull/46661
