### ISSUE TITLE
GraphQL 1.13 multiple definitions feature prevents field redefinition

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#3838] opened 2022-01-13 16:31 UTC
**Describe the bug**

I commented on a [related but closed issue](https://github.com/rmosolgo/graphql-ruby/issues/3417#issuecomment-1010207780) but thought it better to be a bit more precise in a new one.

The GraphQL 1.13.0 release notes state

> Visibility: A schema may contain multiple members with the same name. For each name, GraphQL-Ruby will use the one that returns true for .visible?(context) for each query (and raise an error if multiple objects with the same name are visible). #3651 #3716 #3725

IMO this rather undersells the impact of this change. Previously, it was possible to redefine previously declared fields and in doing so change the definition. Perhaps this is a bad practice, but nevertheless we do it in a few places and as such cannot upgrade to 1.13.0 as far as I can tell, because now GraphQL Ruby interprets re-definition as opting into this new feature, and maintains the old definition, raising `Found two visible definitions for `BaseEdge.cursor`: #<Types::BaseField BaseEdge.cursor: String!>, #<Types::BaseField BaseEdge.cursor: String!>",`

**

**Versions**

`graphql` version: 1.13

**GraphQL schema**

Things I have found that it breaks...

~~Object who shares a field with an interface, but does not share the deprecation reason / description.~~ - This was a red herring

Connections that override the base implementation to add field options.

```ruby
class Types::BaseConnection < Types::RawConnection
  # override page info field added by GraphQL::Types::Relay::ConnectionBehaviors#add_page_info_field
  #   to make it public
  field :page_info, GraphQL::Types::Relay::PageInfo, null: false, description: "Information to aid in pagination.",
        public: true
end

class Types::BaseEdge < Types::BaseObject
  include GraphQL::Types::Relay::EdgeBehaviors

  # override cursor field added by GraphQL::Types::Relay::EdgeBehaviors to make it public
  field :cursor, String, "A cursor for use in pagination.", null: false, public: true

  # this is my solution to adding the option to the node, not sure if it works
  node_type(nil, field_options: { public: true })
end

# Custom Connection Extension to make connection fields public
class Types::PublicConnectionExtension < GraphQL::Schema::Field::ConnectionExtension
  # Override apply from GraphQL::Schema::Field::ConnectionExtension
  def apply
    field.argument(
      :after,
      "String",
      "Returns the elements in the list that come after the specified cursor.",
      required: false,
      public: true
    )
    field.argument(
      :before,
      "String",
      "Returns the elements in the list that come before the specified cursor.",
      required: false,
      public: true
    )
    field.argument(
      :first,
      "Int",
      "Returns the first _n_ elements from the list.",
      required: false,
      public: true
    )
    field.argument(
      :last,
      "Int",
      "Returns the last _n_ elements from the list.",
      required: false,
      public: true
    )
  end
end

class Types::BaseField < GraphQL::Schema::Field
  connection_extension(Types::PublicConnectionExtension)
end

```

**Expected behavior**

It is possible to declare a field to _replace_ an existing definition rather than augment it.

**Actual behavior**

This is not possible (AFAIK?) and instead the definitions co-exist leading to "Found two visible definitions..." errors at schema compile time.

**Comment by rmosolgo** [comment] 2022-01-14 14:26
Sorry for the trouble! Thanks for sharing all those details. Yes, I didn't anticipate these uses of overriding field definitions, but I agree there should be a straight-forward way to accomplish what you're doing above. A couple thoughts, to make sure I understood right: 

- Interface field "inheritance": I think it was _supposed_ to keep working the way you expected it too -- I think it's a bug to have treated that as two different fields. But maybe I'm mistaken. In any case, I'll investigate and follow up here. 
- Connections: Oh, I see -- the call to `field :cursor` adds a new definition, which leads to this error. 

One possibility (discussed briefly in (https://github.com/rmosolgo/graphql-ruby/issues/3743#issuecomment-983784133)) would be something like `override: true`, which would _remove_ an existing definition. (Maybe it could be implemented as `override_field ...` instead, same idea.) I don't love the idea of requiring the caller to know where some field has been implicitly defined elsewhere or not, though 🤔

**Comment by bessey** [comment] 2022-01-15 12:50
>  I don't love the idea of requiring the caller to know where some field has been implicitly defined elsewhere or not, though 🤔

If as you say the interface case is a bug, all the cases I have identified (connection related fields) could be described as explicit. At least, we're explicitly overriding fields we know have been defined, so for my needs this solution seems satisfactory.

That said, if we want to handle fields and arguments with 0 or >=2 previous definitions, what about something like this:

If we want to modify an existing field definition in a way thats agnostic to the number of previous definitions:
```ruby
class Types::BaseEdge < Types::BaseObject
  # initial definition
  include GraphQL::Types::Relay::EdgeBehaviors

  # redefinition
  all_fields[:cursor].map do |field|
    field.redefine_options { |options| options.merge(public: true) }
  end
end
```

Such an API would make it possible for the overrider to only modify certain definitions too:

```ruby
# Initial definitions
field :comments, Types::Comment.connection_type, null: false,
  description: "Comments on this blog post",
  resolver_method: :moderated_comments,
  for_staff: false
field :comments, Types::Comment.connection_type, null: false,
  description: "Comments on this blog post, including unmoderated comments",
  resolver_method: :all_comments,
  for_staff: true

# Redefinition
all_fields[:comments].find { |field| !field[:for_staff] }
  .redefine_options { |options| options.merge(public: true) }

```

**Comment by rmosolgo** [comment] 2022-01-17 16:20
I added a test for the interface field situation in b7fc1ae9b and it passed, so I wrote up a small replication: 


```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.13.5"
end

class Schema < GraphQL::Schema
  module Sellable
    include GraphQL::Schema::Interface
    field :thing, ID, "Sellable description", deprecation_reason: "Something"
  end

  class Product < GraphQL::Schema::Object
    implements Sellable
    field :thing, ID, "Product specific description"
  end

  class QueryType < GraphQL::Schema::Object
    field :product, Product, null: true
    def product
      { thing: "abcd" }
    end
  end

  query QueryType
end

puts Schema.to_definition
# type Product implements Sellable {
#   """
#   Product specific description
#   """
#   thing: ID
# }
#
# type Query {
#   product: Product
# }
#
# interface Sellable {
#   """
#   Sellable description
#   """
#   thing: ID @deprecated(reason: "Something")
# }

pp Schema.execute("{ product { thing } }").to_h
# {"data"=>{"product"=>{"thing"=>"abcd"}}}
```

For me, that worked fine. Does it work when you try it? If so, could you share the full error message and backtrace you're encountering in your real application?

**Comment by RobertWSaunders** [comment] 2022-01-23 15:43
@rmosolgo I ran into some issues with this new behaviour as well. Specifically, I auto generate custom fields on my mutation payload types (think `userErrors`). Previously I could rely on `generate_payload_type` being called **after** all the fields have been defined, this allowed me to check what fields already existed on the payload type, which helped with deciding if I should auto generate one or not. 

I altered my code to work with this new order of payload generation but it caused some headaches since for mutations the payload will get generated at different times depending on if the mutation has a field or not. Mutations without fields won't trigger the payload initialization you added [here](https://github.com/rmosolgo/graphql-ruby/blob/ae2c5f3db73e434104394af37de53f8668ad1be8/lib/graphql/schema/resolver/has_payload_type.rb#L53). I can get around this by triggering the payload type building myself, but I think this weird from a consistency point of view, we should try to keep the order things get created the same despite how things are defined.

**Comment by rmosolgo** [comment] 2022-01-24 18:50
> modify an existing field definition

This is _possible_ now, to some extend: 


```ruby 
class Types::BaseEdge < Types::BaseObject
  # initial definition
  include GraphQL::Types::Relay::EdgeBehaviors

  # redefinition
  all_field_definitions
    .select { |f| f.graphql_name == "cursor" }
    .each { |f| f.public = true }
end
```

There's no method to `redefine_options` because the library passes those options right to `initialize` -- there's no way to re-pass options to initialize -- but instead, you could modify field definitions in place (after adding the writer/update methods).

Want to give that a shot? If it turns out to be common enough problem, we could add a specialized API for it (eg `each_definition("cursor") { |field| ... }`).

**Comment by rmosolgo** [comment] 2022-01-25 16:00
Thanks for sharing, and glad that's working! Please let me know if you run into any more issues with it. I'll close this since I don't have any more plans to work on the problems described here.

**Closed by rmosolgo** 2022-01-25 16:00 UTC

**Comment by bessey** [comment] 2022-01-25 17:54
Actually there's still a case that isn't covered by this solution. I was hoping this would work for the node field itself:

```ruby
class Types::BaseEdge < Types::BaseObject
  include GraphQL::Types::Relay::EdgeBehaviors
  node_type(nil, field_options: { public: true }) # <<<
end
```

However it seems to be a no-op. I guess `node_type` works a treat for custom edges, but not for an abstract base edge. What is the recommended way to modify this? At the point this executes `all_field_definitions` does not include `node`, which is reasonable but presents a challenge

**Comment by bessey** [comment] 2022-01-25 18:01
Ah this works, of course:

```ruby

  # Override GraphQL::Types::Relay::EdgeBehaviors#node_type to make it public
  def self.node_type(node_type = nil, **kwargs)
    super.tap do
      all_field_definitions
        .select { |f| f.graphql_name == "node" }
        .each { |f| f.public = true }
    end
  end
```

**Comment by taylorthurlow** [comment] 2022-03-16 18:42
I ran into this issue after upgrading, caused by my inclusion of `GraphQL::Types::Relay::ConnectionBehaviors` on my application's `BaseConnection` class. The problem is that I wanted to redefine the `pageInfo` field it adds to the type so that it inherits from my application's `BaseField` instead of the built-in one. This way, the `camel_case: false` option on the base field class is applied to the fields on `pageInfo`.

Before I was able to redefine `pageInfo` (technically `page_info`) to use a custom type which just inherits from my application's `BaseObject` and re-includes the `PageInfoBehaviors` class:

```ruby
class MyApp::Types::CustomPageInfoType < MyApp::Types::BaseObject
  include GraphQL::Types::Relay::PageInfoBehaviors
end

class MyApp::Types::BaseConnection < MyApp::Types::BaseObject
  field_class MyApp::Types::BaseField
  edge_type_class MyApp::Types::BaseEdge

  include GraphQL::Types::Relay::ConnectionBehaviors

  edges_nullable false
  edge_nullable false
  node_nullable false

  field :page_info, MyApp::Types::CustomPageInfoType,
        null: false,
        description: "Information to aid in pagination."
end
```

After the upgrade this causes the same duplicate names error. To "solve" it I ended up creating a stand-in module which replicates `GraphQL::Types::Relay::ConnectionBehaviors`:

```ruby
class MyApp::Types::CustomPageInfoType < MyApp::Types::BaseObject
  include GraphQL::Types::Relay::PageInfoBehaviors
end

module MyApp::RelayConnectionBehaviors
  extend GraphQL::Types::Relay::ConnectionBehaviors

  def self.included(child_class)
    child_class.extend(GraphQL::Types::Relay::ConnectionBehaviors::ClassMethods)
    child_class.extend(GraphQL::Types::Relay::DefaultRelay)
    child_class.default_relay(true)
    child_class.has_nodes_field(true)
    child_class.node_nullable(true)
    child_class.edges_nullable(true)
    child_class.edge_nullable(true)
    # NOTE: Crucially, the method missing here normally adds the `pageInfo` field
  end
end

class MyApp::Types::BaseConnection < MyApp::Types::BaseObject
  field_class MyApp::Types::BaseField
  edge_type_class MyApp::Types::BaseEdge

  include MyApp::RelayConnectionBehaviors

  edges_nullable false
  edge_nullable false
  node_nullable false

  field :page_info, MyApp::Types::CustomPageInfoType,
        null: false,
        description: "Information to aid in pagination."
end
```

This allows me to include the original Relay connection behavior without the `pageInfo` field being created, and I am free to create it myself. I'm not all that pleased with this workaround, so if anyone has any other suggestions, I'd love to hear them.
