### ISSUE TITLE
Subscriptions with ActionCable do not work with new Interpeter

### ISSUE THREAD

**Issue by javiercr** [rmosolgo/graphql-ruby#2495] opened 2019-09-25 21:56 UTC
First of all, thank you for all your work on this library!

As it was previously reported, it seems there are some issues with the [new Interpreter](https://graphql-ruby.org/queries/interpreter.html) and [ActionCableSubscriptions](https://graphql-ruby.org/api-doc/1.9.12/GraphQL/Subscriptions/ActionCableSubscriptions). This has been reported in #2446, #2483, but those issues didn't provide a failing case.

To do so I've forked the [evilmartians/chronicles-gql-martian-library](https://github.com/evilmartians/chronicles-gql-martian-library/tree/part-3) project (that's part of the [blog post](https://evilmartians.com/chronicles/graphql-on-rails-3-on-the-way-to-perfection)), and added the minimum set of changes to make it fail: [update the graphql gem](https://github.com/javiercr/chronicles-gql-martian-library/commit/d1ac73f8850067954af0ea7996f504f25cdd9a6c) and [add the new interpreter](https://github.com/javiercr/chronicles-gql-martian-library/commit/7aa60c4f5563c469544265d8cce4313013a24122).

Here are the instructions to reproduce the bug
```
git clone -b graphql-ruby-new-interpreter-bug https://github.com/javiercr/chronicles-gql-martian-library.git
cd chronicles-gql-martian-library
bundle install
rake db:create
rake db:seed
bin/rails s
```

Now you can log in with `john.doe@example.com` and add some items. You'll see this in the console:
```
[ActionCable] Broadcasting to graphql-subscription:30a00d17-d811-4b66-a7de-227f94b01b69: {:result=>{"data"=>nil, "errors"=>[{"message"=>"Cannot return null for non-nullable field Subscription.itemAdded"}]}, :more=>true}
GraphqlChannel transmitting {"result"=>{"data"=>nil, "errors"=>[{"message"=>"Cannot return null for non-nullable field Subscription.itemAdded"}]}, "more"=>true} (via streamed from graphql-subscription:30a00d17-d811-4b66-a7de-227f94b01b69)
```

As you can see, `result.data` is `nil`. It seems that the SubscriptionType field is not receiving any `object`. 

Rolling back to the previous commit (without the new interpeter), everything works perfectly:
```
[ActionCable] Broadcasting to graphql-subscription:23148bba-f699-4eb5-ba08-06721424e274: {:result=>{"data"=>{"itemAdded"=>{"user"=>{"id"=>"2", "email"=>"jane.doe@example.com", "__typename"=>"User"}, "__typename"=>"Item", "id"=>"10", "title"=>"test", "imageUrl"=>"http://testestest.com", "description"=>"tawdawdawdddd"}}}, :more=>true}
GraphqlChannel transmitting {"result"=>{"data"=>{"itemAdded"=>{"user"=>{"id"=>"2", "email"=>"jane.doe@example.com", "__typename"=>"User"}, "__typename"=>"Item", "id"=>"10", "title"=>"test", "imageUrl"=>"http://testestest.com", "description"=>"tawdawdawdddd"}}}, "more"=>true} (via streamed from graphql-subscription:23148bba-f699-4eb5-ba08-06721424e274)
```

I hope this helps, as we're looking forward to using the new interpreter and ActionCable subscriptions. 

Thank you!

**Comment by rmosolgo** [comment] 2019-09-26 14:55
Thanks for your work here, @javiercr! I pulled your branch and tried it locally, and I got the same error. 

I think the difference is that: 

- Before the interpreter, the return value of subscription fields were actually _ignored_ 
- This reduced customizeability and confused people 
- So, in the interpreter, the return value of subscription fields is _used_, and passed along for resolving subscription selections

So, the problem is that the `def item_added` and `def item_updated` methods return `nil`, but the subscriptions have `null: false`. 

The good news is, those empty methods are no longer required for the interpreter. I solved the problem locally by removing them: 

```diff 
~/code/chronicles-gql-martian-library $ git diff
diff --git a/app/graphql/types/subscription_type.rb b/app/graphql/types/subscription_type.rb
index 56e480c..3e46cbd 100644
--- a/app/graphql/types/subscription_type.rb
+++ b/app/graphql/types/subscription_type.rb
@@ -3,11 +3,8 @@
 module Types
   class SubscriptionType < GraphQL::Schema::Object
     extend GraphQL::Subscriptions::SubscriptionRoot

     field :item_added, Types::ItemType, null: false, description: "An item was added"
     field :item_updated, Types::ItemType, null: false, description: "Existing item was updated"
-
-    def item_added; end
-    def item_updated; end
   end
 end
```

Does it work for you to remove those methods?

**Comment by javiercr** [comment] 2019-09-26 16:11
Wow it was that 😅. Yep, it works now both in the test project and in our own private project. That's wonderful.

I guess the docs need an update? Because I've seen other people in the issues struggling with similar issues.

Thank you so much for taking a look to this and finding a workaround so quickly!

**Comment by rmosolgo** [comment] 2019-09-30 19:14
Glad to hear it works for you! You'll find an "Edit this page" link on the docs website, so if you find something to update, please open a PR.

**Closed by rmosolgo** 2019-09-30 19:14 UTC

**Comment by javiercr** [comment] 2020-01-21 16:54
@rmosolgo now that the return value of subscription fields are ignored with the new Interpreter, what's the best way to [Authorize Subscriptions](https://graphql-ruby.org/subscriptions/subscription_type.html#authorizing-subscriptions)?


Let's say that I have a `Conversation` model that has_many  `Message`, and I want to have a subscription every time a message is added:

```ruby
module Types
  class SubscriptionType < GraphQL::Schema::Object
    extend GraphQL::Subscriptions::SubscriptionRoot

    field :message_added, Types::MessageType, null: false do
      description "A message was added"
      argument :conversation_id, ID, required: true
    end
  end
end
```

This subscription takes as argument the conversation_id I want to subscribe to, but the return type is a `MessageType` (the `Message` object that was added).

If I follow the docs for Authorizing subscriptions, I'd add this method to `SubscriptionType`:

```ruby
def message_added(conversation_id:)
  if conversation = ::Conversation.for_user(context[:current_user_id]).find(conversation_id)
    # What to do here?
    # I can't return conversation, as this is not a MessageType
    # but I don't have a message object either.
  else
    raise GraphQL::ExecutionError.new("Can't subscribe to this conversation: #{conversation_id}")
  end
end
```

How could we authorize the subscription without having to return an object of the type defined for it? (as it seems it was possible before the new Interpreter).

Thanks!

**Comment by javiercr** [comment] 2020-01-21 17:07
Never mind, I just found out about [Subscription Classes](https://graphql-ruby.org/subscriptions/subscription_classes.html) which I guess it should handle exactly this scenario. Leaving the previous comment here in case it's helpful for someone else :)
