### ISSUE TITLE
Where are precious milliseconds spent?

### ISSUE THREAD

**Issue by tomaszwro** [rmosolgo/graphql-ruby#3213] opened 2020-11-05 16:19 UTC
I'm making a fairly simple query against a fairly small dataset and it takes a lot of time (350ms+). Notably:
* SQL takes just a little portion of the time — only 10ms
* Only two SQL queries are made (no N+1 stuff)

Log samples:
```
Processing by GraphqlController#execute as */*
  ...
  Product Load (8.2ms)  SELECT "products".* FROM "products" ...
  Image Load (1.0ms)  SELECT "images".* FROM "images" WHERE "images"."product_id" IN ($1, $2, $3 ...
Completed 200 OK in 372ms (Views: 100.2ms | ActiveRecord: 9.1ms | Allocations: 220690)
...
Completed 200 OK in 355ms (Views: 85.9ms | ActiveRecord: 9.3ms | Allocations: 220691)
...
Completed 200 OK in 375ms (Views: 80.1ms | ActiveRecord: 9.2ms | Allocations: 220691)
```

Skylight graph shows long chunks of time spent in app after query execution:

![image](https://user-images.githubusercontent.com/1318234/98245097-b34e8d80-1f70-11eb-8cf6-4be063ffb3d3.png)

I used the `.trace` hook to inspect what's happening and came with two further observations:
1. Field execution times are quite evenly distributed, no clear offender here.
2. `execute_query` block takes for example 196ms but the _sum_ of `execute_field` blocks inside it account only for 62ms of it. It means that 134ms (68%) is spent outside field execution code — which is, I'm assuming, framework code. Seems surprisingly long. Similarly with `execute_query_lazy`. Detailed data of traced event key paths (wall time, summed for path):

```
354.91 execute_multiplex

196.75 execute_multiplex:execute_query
 62.66 execute_multiplex:execute_query:execute_field
  7.78 execute_multiplex:execute_query:authorized

152.18 execute_multiplex:execute_query_lazy
 33.86 execute_multiplex:execute_query_lazy:execute_field
  8.61 execute_multiplex:execute_query_lazy:execute_field_lazy
  2.24 execute_multiplex:execute_query_lazy:authorized

  5.81 execute_multiplex:analyze_multiplex
  3.47 execute_multiplex:analyze_multiplex:validate
  1.39 execute_multiplex:analyze_multiplex:lex
  0.72 execute_multiplex:analyze_multiplex:parse
  0.01 execute_multiplex:analyze_multiplex:analyze_query
```

* [Query under investigation](https://gist.github.com/tomaszwro/411f7164209aa4119212108c42e08f5d)
* Dataset size: 57 products and images. No pagination.
* We were able to replicate this on development — times were slighthly smaller but proportions the same. All times and traces reported here actually come from debugging in development.
* If we trim down the query to one attribute (`products() { cmsId }`), it's order of magnitude faster (30ms vs 350ms++; similar amount of time spent in AR (10ms))
* [Stackprof output for full query](https://gist.github.com/tomaszwro/c592e39a45e40393558e8e491b5bbbd5) — would raw stackprof dump file help more here?
* [Stackprof output for trimmed down query](https://gist.github.com/tomaszwro/d43dce646620b77897dc0495469dbc81) 
* We use `graphql` version 1.11.6 and graphql-batch version 0.4.3.
* We use `GraphQL::Execution::Interpreter` and `GraphQL::Analysis::AST`
* [Some related pieces of code](https://gist.github.com/tomaszwro/540166dabfa6ab78104de8e6b750f736)

So now I basically wonder, why such significant increase in time on the full query, and how can things be made faster. Does above data indicate some problem with implementation?

**Comment by rmosolgo** [comment] 2020-11-06 21:36
Thanks for sharing all those details. _This_ is definitely interesting: 

```
        26  (10.1%)          26  (10.1%)     GraphQL::Query::Context#[]=
```

I added some code to update context in #3139, which was released in 1.11.5. 

To see whether that PR introduced a regression, you could try running your benchmark on 1.11.4. 

> Dataset size: 57 products and images. No pagination.

Is 57 the total of products _and_ images, or are there 57 products _and then_ some images for each product? (I'm wondering how big the result set is. I don't see anything in the schema code or stackprof that looks suspicious, so the next step is to build a small replication if this issue. I want to get a sense of the size of the response for building that replication.)

**Comment by rmosolgo** [comment] 2020-11-10 15:35
Thanks for sharing those details, that's great. I see that 1.11.4 also shows _mostly overhead_ in the stackprof result, it's just _different_ overhead. 8% difference would about line up with the `Context#[]=` time, added in 1.11.5. 

I'm don't think I would get anything out of _more_ requests, but you could try turning up the sample rate (eg `mode: :wall, interval: 10`, https://github.com/tmm1/stackprof#sampling). Also, a memory profiler output might provide some hints, since it shows where objects are allocated: https://github.com/SamSaffron/memory_profiler

Anyways, I'm honestly _not surprised_ given the size of the response. It's quite a big response -- I count about 8500 key-value pairs in about 2900 JSON objects. For each of those, GraphQL-Ruby performs a dynamic field lookup and validates the return value. Sure, it'd be nice if it was _faster_, but I'm not sure I really _can_ make it faster 😅 ! 

There's an existing benchmark which you can run locally: `bundle exec rake bench:profile_large_result > result.txt`.  I'll take a look to see if I can find any speedups.

**Comment by rmosolgo** [comment] 2020-11-10 16:15
I hunted some improvements here: https://github.com/rmosolgo/graphql-ruby/pull/3217

Want to give it a try? 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", branch: "tweak-overhead"
```

Let me know how it looks to you :+1:

**Comment by rmosolgo** [comment] 2020-11-12 19:17
I merged that branch in to master. I hope it improves your benchmark! If you get a try to look into reducing overhead any further and run into trouble, let me know 🍻

**Closed by rmosolgo** 2020-11-12 19:17 UTC

**Comment by andrewhamon** [comment] 2021-01-26 06:23
@rmosolgo I upgraded my company to 1.11.7, eager to try out the new performance fixes. Sadly it did not appear to have a material impact on our production workloads. According to our datadog traces, ~90% of time spent is in graphql-ruby rather than in our application. The cursor on the first screenshot is positioned right about when the deploy should have been fully rolled out, window size is 24hrs.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/5134584/105806244-36c4bd00-5f69-11eb-966e-9d9b14d45e96.png">


<img width="788" alt="image" src="https://user-images.githubusercontent.com/5134584/105806209-26144700-5f69-11eb-8cdf-5250879f37f5.png">


Anyway, I appreciate your efforts nonetheless, I'm hoping I can find some time later this week to do some actual profiling (using the pointers earlier in the thread as my guide) to see if I find anything interesting.

**Comment by rmosolgo** [comment] 2021-01-26 11:55
:+1: Actual profiling output would be great! Since I don't know how  `core-graphql` is collected and sent to datadog, I can't use it for anything. If you get a chance to run some benchmarks and want to investigate it further, please open a new issue with the query you ran, the code you used to collect profiling data, and resulting profile.
