### ISSUE TITLE
input argument of type nullable array getting turned into nil when empty ...?

### ISSUE THREAD

**Issue by breathe** [rmosolgo/graphql-ruby#2714] opened 2020-02-02 22:47 UTC
I have a mutation with an argument like this:

```
argument :items_referencing_mod_group, [Inputs::UpdateRefInput], "New set of items that should reference this mod group", required: false
```

with

```
class Inputs::UpdateRefInput < Types::BaseInputObject
  description "Attributes to update on a menu modifier"
  argument :ref, ID, "Identifies what to point to", required: false
end
```

If I supply the value of items_referencing_mod_group with an empty array, my resolver method receives the argument value as nil rather than empty array ...  this seems like a bug?  I've tried with `:ref` parameter on `UpdateRefInput` with `required: false` and `required: true` and same effect either way

**Comment by rmosolgo** [comment] 2020-02-05 17:14
Uh oh! How are you providing an empty array to GraphQL? Is it  coming through a Rails controller? If so, possible duplicate of https://github.com/rmosolgo/graphql-ruby/issues/2592 -- Rails does this coercion. 

If not, could you please share an  example `.execute(...)` call that demonstrates the bug? It's definitely tricky to get empty-value handling right, so there might be a bug!

**Comment by breathe** [comment] 2020-02-07 04:24
Wow!!  Thank you so much!! @rmosolgo 

omg that's a horrific coercion ...  (i'm new to rails and I very much dislike it ... -- graphql-ruby gem is quite nice tho so thank you!).

This is coercion within a rails controller is definitely the cause of the issue I'm seeing ... so far I've only learned enough rails to hook up ruby-graphql and get out of the ecosystem -- but will followup with the fix needed to turn off this coercion behavior on the controller handling my graphql queries ...

**Comment by breathe** [comment] 2020-02-08 04:40
I added graphql to an existing rails application -- and I don't feel at all confident enough to change the behavior of deep_munge on the rest of my rails app.

Unfortunately the configuration option provided by rails for this is global ... this is the horrible middleware hack I came up with to provide a way to selectively disable deep_munge in certain parts of the application ...


```
module ActionDispatch
  class Request
    class Utils
      @__original_perform_deep_munge_setting = ActionDispatch::Request::Utils.perform_deep_munge

      def self.perform_deep_munge
        if Thread.current[:__checkmate_conditionally_disable_deep_munge] == true
          # disable this annoying behavior
          false
        else
          # return the normal setting for this
          @__original_perform_deep_munge_setting
        end
      end
    end
  end
end

class ConditionallyDisableDeepMungeMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    # do nothing if not targeting blessed "no deep munge" paths
    return @app.call(env) if env["REQUEST_PATH"].nil?
    return @app.call(env) unless env["REQUEST_PATH"].starts_with?("/token_api/graphql")

    Thread.current[:__checkmate_conditionally_disable_deep_munge] = true
    res = @app.call(env)
    Thread.current[:__checkmate_conditionally_disable_deep_munge] = false
    return res
  end
end
```

and insert the middleware before the `ActionDispatch::ParamsParser` middleware from an initializaer ...

```
Rails.application.configure do
  config.middleware.insert_before ActionDispatch::ParamsParser, ConditionallyDisableDeepMungeMiddleware
end
```

**Comment by rmosolgo** [comment] 2020-02-11 12:06
Thanks for sharing your solution here, glad you found something that works!

**Closed by rmosolgo** 2020-02-11 12:06 UTC
