### ISSUE TITLE
Resolver raises an exception since v1.11.0

### ISSUE THREAD

**Issue by engwan** [rmosolgo/graphql-ruby#3113] opened 2020-08-26 13:01 UTC
**Describe the bug**

I tried upgrading the Gem and saw a lot of failures in our test suite. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40416

Errors looked like:

```ruby
NoMethodError:
  undefined method `object' for #<Project id:1352 namespace1242/project1288>>
  Did you mean?  object_id
```

I traced it back to https://github.com/rmosolgo/graphql-ruby/commit/f820c793dffe42d9176562205c9e6d276bdb02b8 which added `object.object` calls to get the parent.

Adding a `if object.is_a?(GraphQL::Schema::Object)` check just like  what we already do in https://github.com/rmosolgo/graphql-ruby/blob/v1.11.4/lib/graphql/schema/field/connection_extension.rb#L55-L57 fixes the issue.

@rmosolgo I don't know much about the connection extension internals and I'm wondering if this is a bug and if that is the correct fix? Or is this intended and we have to change something on the application side?

**Comment by rmosolgo** [comment] 2020-08-26 20:05
Hey, sorry about the hangup! 

I tried to find a full backtrace in the build that you linked to, but I couldn't find one. (It seems like GraphQL errors were being caught with generic "internal server errors".) 

Could you please share a full backtrace? 

Or, if you want to go ahead with a patch like you suggested, that sounds good to me, as long as you don't mind adding a test for it. (I can't quite tell what went wrong without the backtrace, but a PR with a test would be fine, too :+1:)

**Comment by engwan** [comment] 2020-08-27 01:27
Sorry, should've posted it. Here's a sample backtrace from https://gitlab.com/gitlab-org/gitlab/-/jobs/703175424:

```
     NoMethodError:
       undefined method `object' for #<Project id:1352 namespace1242/project1288>>
       Did you mean?  object_id
     # ./vendor/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_methods.rb:432:in `method_missing'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field/connection_extension.rb:53:in `block in after_resolve'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:112:in `after_lazy'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field/connection_extension.rb:28:in `after_resolve'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:735:in `block (2 levels) in with_extensions'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:732:in `each'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:732:in `each_with_index'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:732:in `block in with_extensions'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:112:in `after_lazy'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:731:in `with_extensions'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:550:in `block (2 levels) in resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:112:in `after_lazy'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:545:in `block in resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:112:in `after_lazy'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/field.rb:539:in `resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/member/instrumentation.rb:80:in `call'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/member/instrumentation.rb:80:in `call'
     # ./lib/gitlab/graphql/authorize/authorize_field_service.rb:18:in `block in authorized_resolve'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/field.rb:136:in `resolve'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:321:in `call'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/tracing.rb:66:in `trace'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:128:in `resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:85:in `each'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:85:in `resolve_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:284:in `resolve_value'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:278:in `resolve_value'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:213:in `continue_resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:184:in `continue_or_wait'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:157:in `resolve_field'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:85:in `each'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:85:in `resolve_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/tracing.rb:66:in `trace'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/execute.rb:31:in `begin_query'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:112:in `begin_query'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:82:in `map'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/tracing.rb:66:in `trace'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:58:in `run_queries'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/execution/multiplex.rb:48:in `run_all'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:1642:in `multiplex'
     # ./vendor/ruby/2.6.0/gems/graphql-1.11.4/lib/graphql/schema.rb:1613:in `execute'
```

**Comment by engwan** [comment] 2020-09-03 17:10
@rmosolgo I think I found the root cause of this issue. We are passing the inner object to `#with_extensions` instead of the GraphQL wrapped one.

So doing this fixes it for me:

```diff
diff --git a/lib/graphql/schema/field.rb b/lib/graphql/schema/field.rb
index dfc3aa3f1..da6c6fa86 100644
--- a/lib/graphql/schema/field.rb
+++ b/lib/graphql/schema/field.rb
@@ -547,7 +547,7 @@ module GraphQL
               # Then if it passed, resolve the field
               if @resolve_proc
                 # Might be nil, still want to call the func in that case
-                with_extensions(inner_obj, ruby_args, query_ctx) do |extended_obj, extended_args|
+                with_extensions(after_obj, ruby_args, query_ctx) do |extended_obj, extended_args|
                   # Pass the GraphQL args here for compatibility:
                   @resolve_proc.call(extended_obj, args, ctx)
                 end
```

Is passing the `inner_obj` intended? I saw that in older versions we were passing the outer object: https://github.com/rmosolgo/graphql-ruby/blob/8eaef47cf0498f0012a3132a7ea9402c46b89208/lib/graphql/schema/field.rb#L485

**Comment by engwan** [comment] 2020-09-17 17:17
@rmosolgo I dug into this again and found more details about this bug. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/40416#note_414534485

The bug happens when using a resolve proc that returns a connection type. When a resolver class is used, we pass the `GraphQL::Schema::Object` to `#with_extensions`. But when a proc is provided, we incorrectly pass the `inner_obj`.

And the recent changes to `ConnectionExtension` which now calls `object.object` to get the parent surfaced this problem.

Can you recommend a file to write a spec for this? I'm not familiar with this codebase and am having a hard time finding the right way to write a failing spec for this.

**Comment by rmosolgo** [comment] 2020-09-22 14:50
Thanks for sharing what you found as you looked into this, and sorry I wasn't more help along the way 😅 ! 

If the problem is with a `resolve:` proc, then my recommendation is to rewrite the resolve proc as a resolver. In 1.12.x, the last vestiges of the legacy schema definition (`.define` & friends) will be marked as deprecated, so you might as well make the migration. 

If you find something that doesn't migrate well, please open a new issue to discuss it! 

If you would rather make a PR, I'd be happy to accept it. As far as a test, the easiest thing to do is probably to add an isolated example schema and run a query on it, something like this: 

https://github.com/rmosolgo/graphql-ruby/blob/183f318a18053870b95b0ce08e30da23c2e13278/spec/graphql/schema/field_spec.rb#L432-L476

And you could use a `resolve:` proc in the test schema like the one in your app.

**Closed by rmosolgo** 2020-09-22 14:50 UTC
