### ISSUE TITLE
Schema.from_definition and implements GraphQL::Relay::Node.interface

### ISSUE THREAD

**Issue by jdsjr** [rmosolgo/graphql-ruby#1082] opened 2017-11-08 19:51 UTC
I need to support a relay client and was looking at http://graphql-ruby.org/relay/object_identification.html.  However, I am using GraphQL::Schema.from_definition to get my schema, and not defining each type separately.  Is there an approach for supporting relay when using "from_definition" and the "Resolving with a Single Function" approach?

**Comment by astorije** [comment] 2017-11-14 04:59
Is this a duplicate of https://github.com/rmosolgo/graphql-ruby/issues/1043?

**Comment by rmosolgo** [comment] 2017-11-14 15:31
Definitely similar, but a slightly different problem. 

In both cases, the issue is that `Schema.from_definition` can't be used with the gem's Relay support. This issue is asking how to use `Node`, but the other issue is about `Connection.nodes`.

**Comment by rmosolgo** [comment] 2020-02-19 21:31
It's been over two years... I think I have to admit I'm not going to work on this! When using `.from_definition`, you'll have to implement your own loading schema. (TBH, it would be possible to parse `@loads(...)` from schema definitions and turn them into `loads:` configurations, etc, but I'm not going to work on it.)

**Closed by rmosolgo** 2020-02-19 21:31 UTC
