### ISSUE TITLE
Apollo 2 ActionCableLink with authentication

### ISSUE THREAD

**Issue by chrise86** [rmosolgo/graphql-ruby#1658] opened 2018-07-10 12:12 UTC
The example shows how to do authentication (by setting headers) for version 1 but not version 2. I can't seem to get this to work, the headers are empty when the connection is made to the server. Can anyone shed some light on this?

I'm currently trying to setup auth like this:

```javascript
import { setContext } from 'apollo-link-context'

const authLink = setContext(async (_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = await AsyncStorage.getItem('token')

  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Token token=${token}` : null
    }
  }
})

const cable = ActionCable.createConsumer(cableUrl)
const actionCableLink = new ActionCableLink({ cable })
const link = ApolloLink.from([authLink, actionCableLink])
const client = new ApolloClient({ link, cache })
```

**Comment by thefliik** [comment] 2018-07-10 15:54
@chrise86 the way I've successfully added headers looks like the following
```
constructor(
    private apollo: Apollo,
    private transferState: TransferState,
    private httpLinkConstructor: HttpLink,
    private cookieService: CookieService,
  ) {

    // .... other stuff

    let headers: { [name: string]: string } = {};

    // get the authentication token from local storage if it exists
    const token = this.cookieService.get('auth_token');

    if (token) headers.authorization = token;

    const httpLink = this.httpLinkConstructor.create({
      uri,
      headers: new HttpHeaders(headers),
      includeExtensions: true,
      withCredentials: true,
    });

    // ... some other stuff

    this.link = ApolloLink.from([extensionsLink, stateLink, httpLink]);

    const apolloOptions: ApolloClientOptions<NormalizedCacheObject> = {
      link: this.link,
      cache: this.cache,
    };

    this.apollo.create(apolloOptions);
```

**Comment by chrise86** [comment] 2018-07-10 15:55
@thefliik that is pretty much the same as what I have isn't it? Neither works for ActionCable though

**Comment by thefliik** [comment] 2018-07-10 15:56
I notice I have a "withCredentials" option that your missing. I can't remember if that's specific to the Angular implementation, but that might be the cause of the issue.

**Comment by chrise86** [comment] 2018-07-10 15:58
@thefliik my implementation works fine with httplink, but the issue here is that the actioncable link is different to the httplink, and setting headers does not work.

**Comment by thefliik** [comment] 2018-07-10 18:54
Ah, I understand now. I haven't yet needed to set up an actioncable link myself.

**Comment by casiodk** [comment] 2018-11-16 19:20
does anybody know how to achieve this?

**Comment by FX-HAO** [comment] 2019-06-12 08:50
Any progress?

**Comment by FX-HAO** [comment] 2019-06-12 10:21
Seems like ActionCable doesn't support additional headers, so a workaround is `const cable = ActionCable.createConsumer('ws://localhost:3334/cable?token=${token}`
And in cable connection you can get the token with the following:
```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    def connect
      token = request.params[:token]
    end
  end
end
```

**Comment by martinek** [comment] 2019-09-04 09:02
@kidcosmic Should that work? According to https://developer.mozilla.org/en-US/docs/Web/API/WebSocket WebSocket constructor does not take third argument.

**Comment by kidcosmic** [comment] 2019-09-04 09:06
@martinek good point. We’re using this in React Native in production. Works fine there. You’d have to investigate if this works across browsers, or how you can modify the Websocket class to make it work.

**Comment by martinek** [comment] 2019-09-04 09:07
@kidcosmic Looks like it is not currently possible to modify websocket headers in browsers. https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

**Comment by rmosolgo** [comment] 2020-03-02 18:04
Thanks for sharing your solutions here. I don't see any specific work to be done on the javascript client, so closing this.

**Closed by rmosolgo** 2020-03-02 18:04 UTC
