### ISSUE TITLE
no implicit conversion of #<Class:0x00007ff4cd3b8728> into Hash

### ISSUE THREAD

**Issue by fisherboat** [rmosolgo/graphql-ruby#2545] opened 2019-10-14 11:24 UTC
![image](https://user-images.githubusercontent.com/2755103/66747765-e599d280-eeb7-11e9-9aa8-abde3049da01.png)

![image](https://user-images.githubusercontent.com/2755103/66747816-06fabe80-eeb8-11e9-9718-1b88275d2389.png)

![image](https://user-images.githubusercontent.com/2755103/66747846-1d087f00-eeb8-11e9-939b-09908ce937f7.png)

ruby: 2.6.0
rails: 6.0.0

**Comment by jmourell** [comment] 2019-10-14 15:21
I'm having the same issue. But I'm new to rails and ruby so I'm not sure if it's just my set up is wrong, although I'm just following the official docs pretty - much.

**Comment by daemonsy** [comment] 2019-10-14 18:42
Hi people, assuming you're on `1.9.13`, can you try if `1.9.14` fixes the issue?

@rmosolgo fixed an issue that looks really similar to this one on #2541

**Comment by rmosolgo** [comment] 2019-10-14 18:44
Yes, this looks like a duplicate of https://github.com/rmosolgo/graphql-ruby/issues/2537 

Please try `1.9.14`. Some code in the previous version didn't work with the generated `BaseField`, sorry! 

Please reopen this if you encounter trouble after updating to 1.9.14.

**Closed by rmosolgo** 2019-10-14 18:44 UTC
